// firefox_parity_data.h - GENERATED by tools/gen_firefox_parity.py from the
// Firefox source tree at hg mozilla-release 9ce1ee6baeb9a3c326dbd180bdece65d8fc2eadc. Do not edit by hand.
//
// Data the parity layer of freetype.cpp takes verbatim from
// Firefox; the file naming each table is given above it.

#ifndef FIREFOX_PARITY_DATA_H_INCLUDED
#define FIREFOX_PARITY_DATA_H_INCLUDED

namespace firefox_parity {

// modules/libpref/init/all.js font.blacklist.underline_offset, the list
// gfxPlatformFontList::LoadBadUnderlineList loads and gfxDWriteFontList
// applies to a family (gfxFcPlatformFontList never does).
constexpr const char* kBadUnderlineFamilies[] = {
    "FangSong",
    "Gulim",
    "GulimChe",
    "MingLiU",
    "MingLiU-ExtB",
    "MingLiU_HKSCS",
    "MingLiU-HKSCS-ExtB",
    "MS Gothic",
    "MS Mincho",
    "MS PGothic",
    "MS PMincho",
    "MS UI Gothic",
    "PMingLiU",
    "PMingLiU-ExtB",
    "SimHei",
    "SimSun",
    "SimSun-ExtB",
    "Hei",
    "Kai",
    "Apple LiGothic",
    "Apple LiSung",
    "Osaka",
};
constexpr unsigned kBadUnderlineFamilyCount = 22;

// The threads WebRender rasterizes glyphs on: gfx/webrender_bindings/src/
// bindings.rs ("WRWorker<tag>#<n>", "WrGlyphRasterizer") and gfx/wr/webrender/
// src/renderer/init.rs ("WRRenderBackend#<n>"). Gecko's NS_SetCurrentThreadName
// keeps the first seven characters of a name longer than 15 bytes, so the
// first seven are what a thread's comm is matched on.
constexpr const char* kWebRenderThreadPrefixes[] = {
    "WRWorke",
    "WrGlyph",
    "WRRende",
};
constexpr unsigned kWebRenderThreadPrefixCount = 3;

// The two gamma pairs a page is drawn with, on
// ScaledFontDWrite::GetWRFontInstanceOptions' percent scale.
//
// kPage is the system values, which reach WebRender's glyph rasterizer and
// every Skia consumer through gfx.font_rendering.freetype.*. kBlob is
// gfx/2d/DWriteSettings.cpp's own initializers, sGamma{2.2f} and
// sEnhancedContrast{1.0f}, which Firefox's blob rasterizer is reached
// before gfxVars replace. DrawTargetSkia::UpdateSurfaceProps has no such
// split on Linux, where the prefs are in place before anything draws.
constexpr int kPageGamma = 180;
constexpr int kPageEnhancedContrast = 100;
constexpr int kBlobGamma = 220;
constexpr int kBlobEnhancedContrast = 100;

// modules/libpref/init/StaticPrefList.yaml
// gfx.font_rendering.directwrite.bold_simulation: 0 never the DirectWrite
// bold simulation, 1 installed fonts only (not webfonts, not COLR), 2 all
// but COLR (gfxDWriteFontEntry::CreateFontInstance).
constexpr int kDirectWriteBoldSimulation = 1;

// gfx/thebes/gfxWindowsPlatform.cpp gfxWindowsPlatform::GetCommonFallbackFonts:
// the families Windows tries for a script after the font group's own and the
// pref fonts, before DirectWrite's system fallback. Script codes are the
// values of mozilla::intl::Script in intl/components/src/UnicodeScriptCodes.h.
// The conditions each AppendElement sits under are carried rather than
// flattened, so the replacement can evaluate them the way the source does.
enum CommonFallbackCondition
{
    kFallbackAlways = 0,
    kFallbackColor = 1,          // PrefersColor(aPresentation)
    kFallbackNotColor = 2,       // !PrefersColor(aPresentation)
    kFallbackSupplementary = 3,  // aCh > 0xFFFF
    kFallbackPunctOrCommon = 4,  // COMMON, or the symbol/punctuation test
};
struct CommonFallbackFamily
{
    const char* name;
    int condition;
};
struct CommonFallbackRule
{
    unsigned script_first, script_count, family_first, family_count;
};
// Script::COMMON, which the tail's condition tests for by name.
[[maybe_unused]] constexpr short kScriptCommon = 0;
[[maybe_unused]] const short kWindowsCommonFallbackScripts[] = {
    5, 172, 73, 17,   // BOPOMOFO, HAN_WITH_BOPOMOFO, SIMPLIFIED_HAN, HAN
    74, 212, 20, 22,   // TRADITIONAL_HAN, TRADITIONAL_HAN_WITH_LATIN, HIRAGANA, KATAKANA
    54, 105, 18, 173,   // KATAKANA_OR_HIRAGANA, JAPANESE, HANGUL, JAMO
    119, 41, 27, 39,   // KOREAN, YI, MONGOLIAN, TIBETAN
    90, 200, 34, 95,   // PHAGS_PA, ARABIC_NASTALIQ, SYRIAC, ESTRANGELO_SYRIAC
    37, 4, 10, 15,   // THAANA, BENGALI, DEVANAGARI, GUJARATI
    16, 21, 26, 31,   // GURMUKHI, KANNADA, MALAYALAM, ORIYA
    35, 36, 33, 118,   // TAMIL, TELUGU, SINHALA, CHAKMA
    115, 109, 152, 28,   // MEETEI_MAYEK, OL_CHIKI, SORA_SOMPENG, MYANMAR
    23, 24, 38, 52,   // KHMER, LAO, THAI, TAI_LE
    55, 59, 78, 12,   // BUGINESE, NEW_TAI_LUE, JAVANESE, GEORGIAN
    72, 131, 11, 167,   // KHUTSURI, LISU, ETHIOPIC, ADLAM
    87, 50, 60, 99,   // NKO, OSMANYA, TIFINAGH, VAI
    40, 6, 171, 46,   // CANADIAN_ABORIGINAL, CHEROKEE, OSAGE, BRAILLE
    9, 65, 104, 101,   // DESERET, BRAHMI, CARIAN, CUNEIFORM
    47, 71, 56, 13,   // CYPRIOT, EGYPTIAN_HIEROGLYPHS, GLAGOLITIC, GOTHIC
    116, 122, 125, 57,   // IMPERIAL_ARAMAIC, INSCRIPTIONAL_PAHLAVI, INSCRIPTIONAL_PARTHIAN, KHAROSHTHI
    107, 108, 141, 29,   // LYCIAN, LYDIAN, MEROITIC_CURSIVE, OGHAM
    30, 61, 133, 88,   // OLD_ITALIC, OLD_PERSIAN, OLD_SOUTH_ARABIAN, OLD_TURKIC
    91, 32, 51, 53,   // PHOENICIAN, RUNIC, SHAVIAN, UGARITIC
    161, 117, 62, 130,   // AHOM, AVESTAN, BALINESE, BAMUM
    134, 63, 168, 44,   // BASSA_VAH, BATAK, BHAIKSUKI, BUHID
    159, 66, 7, 135,   // CAUCASIAN_ALBANIAN, CHAM, COPTIC, DUPLOYAN
    136, 137, 182, 43,   // ELBASAN, GRANTHA, HANIFI_ROHINGYA, HANUNOO
    162, 120, 79, 157,   // HATRAN, KAITHI, KAYAH_LI, KHOJKI
    145, 82, 48, 83,   // KHUDAWADI, LEPCHA, LIMBU, LINEAR_A
    49, 160, 84, 121,   // LINEAR_B, MAHAJANI, MANDAIC, MANICHAEAN
    169, 140, 86, 92,   // MARCHEN, MENDE_KIKAKUI, MEROITIC_HIEROGLYPHS, MIAO
    163, 149, 164, 143,   // MODI, MRO, MULTANI, NABATAEAN
    170, 76, 142, 89,   // NEWA, OLD_HUNGARIAN, OLD_NORTH_ARABIAN, OLD_PERMIC
    75, 144, 165, 123,   // PAHAWH_HMONG, PALMYRENE, PAU_CIN_HAU, PSALTER_PAHLAVI
    110, 126, 111, 151,   // REJANG, SAMARITAN, SAURASHTRA, SHARADA
    166, 113, 58, 42,   // SIDDHAM, SUNDANESE, SYLOTI_NAGRI, TAGALOG
    45, 106, 127, 153,   // TAGBANWA, TAI_THAM, TAI_VIET, TAKRI
    158, 188, 146,   // TIRHUTA, WANCHO, WARANG_CITI
};
[[maybe_unused]] const CommonFallbackFamily kWindowsCommonFallbackFamilies[] = {
    { .name = "Segoe UI Emoji", .condition = 1 },
    { .name = "Twemoji Mozilla", .condition = 1 },
    { .name = "SimSun", .condition = 0 },
    { .name = "SimSun-ExtB", .condition = 3 },
    { .name = "MingLiU", .condition = 0 },
    { .name = "MingLiU-ExtB", .condition = 3 },
    { .name = "Yu Gothic", .condition = 0 },
    { .name = "MS PGothic", .condition = 0 },
    { .name = "Malgun Gothic", .condition = 0 },
    { .name = "Microsoft Yi Baiti", .condition = 0 },
    { .name = "Mongolian Baiti", .condition = 0 },
    { .name = "Microsoft Himalaya", .condition = 0 },
    { .name = "Microsoft PhagsPa", .condition = 0 },
    { .name = "Urdu Typesetting", .condition = 0 },
    { .name = "Estrangelo Edessa", .condition = 0 },
    { .name = "MV Boli", .condition = 0 },
    { .name = "Vrinda", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Kokila", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Shruti", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Raavi", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Tunga", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Kartika", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Kalinga", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Latha", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Gautami", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Iskoola Pota", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Nirmala UI", .condition = 0 },
    { .name = "Myanmar Text", .condition = 0 },
    { .name = "Khmer UI", .condition = 0 },
    { .name = "Lao UI", .condition = 0 },
    { .name = "Tahoma", .condition = 0 },
    { .name = "Leelawadee UI", .condition = 0 },
    { .name = "Microsoft Tai Le", .condition = 0 },
    { .name = "Leelawadee UI", .condition = 0 },
    { .name = "Microsoft New Tai Lue", .condition = 0 },
    { .name = "Javanese Text", .condition = 0 },
    { .name = "Segoe UI", .condition = 0 },
    { .name = "Nyala", .condition = 0 },
    { .name = "Ebrima", .condition = 0 },
    { .name = "Ebrima", .condition = 0 },
    { .name = "Euphemia", .condition = 0 },
    { .name = "Gadugi", .condition = 0 },
    { .name = "Segoe UI Symbol", .condition = 0 },
    { .name = "Segoe UI Historic", .condition = 0 },
    { .name = "Noto Serif Ahom", .condition = 0 },
    { .name = "Noto Sans Avestan", .condition = 0 },
    { .name = "Noto Sans Balinese", .condition = 0 },
    { .name = "Noto Sans Bamum", .condition = 0 },
    { .name = "Noto Sans Bassa Vah", .condition = 0 },
    { .name = "Noto Sans Batak", .condition = 0 },
    { .name = "Noto Sans Bhaiksuki", .condition = 0 },
    { .name = "Noto Sans Buhid", .condition = 0 },
    { .name = "Noto Sans Caucasian Albanian", .condition = 0 },
    { .name = "Noto Sans Cham", .condition = 0 },
    { .name = "Noto Sans Coptic", .condition = 0 },
    { .name = "Noto Sans Duployan", .condition = 0 },
    { .name = "Noto Sans Elbasan", .condition = 0 },
    { .name = "Noto Sans Grantha", .condition = 0 },
    { .name = "Noto Sans Hanifi Rohingya", .condition = 0 },
    { .name = "Noto Sans Hanunoo", .condition = 0 },
    { .name = "Noto Sans Hatran", .condition = 0 },
    { .name = "Noto Sans Kaithi", .condition = 0 },
    { .name = "Noto Sans Kayah Li", .condition = 0 },
    { .name = "Noto Sans Khojki", .condition = 0 },
    { .name = "Noto Sans Khudawadi", .condition = 0 },
    { .name = "Noto Sans Lepcha", .condition = 0 },
    { .name = "Noto Sans Limbu", .condition = 0 },
    { .name = "Noto Sans Linear A", .condition = 0 },
    { .name = "Noto Sans Linear B", .condition = 0 },
    { .name = "Noto Sans Mahajani", .condition = 0 },
    { .name = "Noto Sans Mandaic", .condition = 0 },
    { .name = "Noto Sans Manichaean", .condition = 0 },
    { .name = "Noto Sans Marchen", .condition = 0 },
    { .name = "Noto Sans Mende Kikakui", .condition = 0 },
    { .name = "Noto Sans Meroitic", .condition = 0 },
    { .name = "Noto Sans Miao", .condition = 0 },
    { .name = "Noto Sans Modi", .condition = 0 },
    { .name = "Noto Sans Mro", .condition = 0 },
    { .name = "Noto Sans Multani", .condition = 0 },
    { .name = "Noto Sans Nabataean", .condition = 0 },
    { .name = "Noto Sans Newa", .condition = 0 },
    { .name = "Noto Sans Old Hungarian", .condition = 0 },
    { .name = "Noto Sans Old North Arabian", .condition = 0 },
    { .name = "Noto Sans Old Permic", .condition = 0 },
    { .name = "Noto Sans Pahawh Hmong", .condition = 0 },
    { .name = "Noto Sans Palmyrene", .condition = 0 },
    { .name = "Noto Sans Pau Cin Hau", .condition = 0 },
    { .name = "Noto Sans Psalter Pahlavi", .condition = 0 },
    { .name = "Noto Sans Rejang", .condition = 0 },
    { .name = "Noto Sans Samaritan", .condition = 0 },
    { .name = "Noto Sans Saurashtra", .condition = 0 },
    { .name = "Noto Sans Sharada", .condition = 0 },
    { .name = "Noto Sans Siddham", .condition = 0 },
    { .name = "Noto Sans Sundanese", .condition = 0 },
    { .name = "Noto Sans Syloti Nagri", .condition = 0 },
    { .name = "Noto Sans Tagalog", .condition = 0 },
    { .name = "Noto Sans Tagbanwa", .condition = 0 },
    { .name = "Noto Sans Tai Tham", .condition = 0 },
    { .name = "Noto Sans Tai Viet", .condition = 0 },
    { .name = "Noto Sans Takri", .condition = 0 },
    { .name = "Noto Sans Tirhuta", .condition = 0 },
    { .name = "Noto Sans Wancho", .condition = 0 },
    { .name = "Noto Sans Warang Citi", .condition = 0 },
    { .name = "Arial", .condition = 0 },
    { .name = "Segoe UI", .condition = 4 },
    { .name = "Segoe UI Symbol", .condition = 4 },
    { .name = "Cambria Math", .condition = 4 },
    { .name = "Arial Unicode MS", .condition = 0 },
    { .name = "Segoe UI Emoji", .condition = 2 },
    { .name = "Twemoji Mozilla", .condition = 2 },
};
[[maybe_unused]] const CommonFallbackRule kWindowsCommonFallbackRules[] = {
    { .script_first = 0, .script_count = 4, .family_first = 2, .family_count = 2 },
    { .script_first = 4, .script_count = 2, .family_first = 4, .family_count = 2 },
    { .script_first = 6, .script_count = 4, .family_first = 6, .family_count = 2 },
    { .script_first = 10, .script_count = 3, .family_first = 8, .family_count = 1 },
    { .script_first = 13, .script_count = 1, .family_first = 9, .family_count = 1 },
    { .script_first = 14, .script_count = 1, .family_first = 10, .family_count = 1 },
    { .script_first = 15, .script_count = 1, .family_first = 11, .family_count = 1 },
    { .script_first = 16, .script_count = 1, .family_first = 12, .family_count = 1 },
    { .script_first = 17, .script_count = 1, .family_first = 13, .family_count = 1 },
    { .script_first = 18, .script_count = 2, .family_first = 14, .family_count = 1 },
    { .script_first = 20, .script_count = 1, .family_first = 15, .family_count = 1 },
    { .script_first = 21, .script_count = 1, .family_first = 16, .family_count = 2 },
    { .script_first = 22, .script_count = 1, .family_first = 18, .family_count = 2 },
    { .script_first = 23, .script_count = 1, .family_first = 20, .family_count = 2 },
    { .script_first = 24, .script_count = 1, .family_first = 22, .family_count = 2 },
    { .script_first = 25, .script_count = 1, .family_first = 24, .family_count = 2 },
    { .script_first = 26, .script_count = 1, .family_first = 26, .family_count = 2 },
    { .script_first = 27, .script_count = 1, .family_first = 28, .family_count = 2 },
    { .script_first = 28, .script_count = 1, .family_first = 30, .family_count = 2 },
    { .script_first = 29, .script_count = 1, .family_first = 32, .family_count = 2 },
    { .script_first = 30, .script_count = 1, .family_first = 34, .family_count = 2 },
    { .script_first = 31, .script_count = 4, .family_first = 36, .family_count = 1 },
    { .script_first = 35, .script_count = 1, .family_first = 37, .family_count = 1 },
    { .script_first = 36, .script_count = 1, .family_first = 38, .family_count = 1 },
    { .script_first = 37, .script_count = 1, .family_first = 39, .family_count = 1 },
    { .script_first = 38, .script_count = 1, .family_first = 40, .family_count = 2 },
    { .script_first = 39, .script_count = 1, .family_first = 42, .family_count = 1 },
    { .script_first = 40, .script_count = 1, .family_first = 43, .family_count = 1 },
    { .script_first = 41, .script_count = 1, .family_first = 44, .family_count = 1 },
    { .script_first = 42, .script_count = 1, .family_first = 45, .family_count = 1 },
    { .script_first = 43, .script_count = 3, .family_first = 46, .family_count = 1 },
    { .script_first = 46, .script_count = 1, .family_first = 47, .family_count = 2 },
    { .script_first = 47, .script_count = 5, .family_first = 49, .family_count = 1 },
    { .script_first = 52, .script_count = 1, .family_first = 50, .family_count = 1 },
    { .script_first = 53, .script_count = 2, .family_first = 51, .family_count = 1 },
    { .script_first = 55, .script_count = 2, .family_first = 52, .family_count = 1 },
    { .script_first = 57, .script_count = 23, .family_first = 53, .family_count = 1 },
    { .script_first = 80, .script_count = 1, .family_first = 54, .family_count = 1 },
    { .script_first = 81, .script_count = 1, .family_first = 55, .family_count = 1 },
    { .script_first = 82, .script_count = 1, .family_first = 56, .family_count = 1 },
    { .script_first = 83, .script_count = 1, .family_first = 57, .family_count = 1 },
    { .script_first = 84, .script_count = 1, .family_first = 58, .family_count = 1 },
    { .script_first = 85, .script_count = 1, .family_first = 59, .family_count = 1 },
    { .script_first = 86, .script_count = 1, .family_first = 60, .family_count = 1 },
    { .script_first = 87, .script_count = 1, .family_first = 61, .family_count = 1 },
    { .script_first = 88, .script_count = 1, .family_first = 62, .family_count = 1 },
    { .script_first = 89, .script_count = 1, .family_first = 63, .family_count = 1 },
    { .script_first = 90, .script_count = 1, .family_first = 64, .family_count = 1 },
    { .script_first = 91, .script_count = 1, .family_first = 65, .family_count = 1 },
    { .script_first = 92, .script_count = 1, .family_first = 66, .family_count = 1 },
    { .script_first = 93, .script_count = 1, .family_first = 67, .family_count = 1 },
    { .script_first = 94, .script_count = 1, .family_first = 68, .family_count = 1 },
    { .script_first = 95, .script_count = 1, .family_first = 69, .family_count = 1 },
    { .script_first = 96, .script_count = 1, .family_first = 70, .family_count = 1 },
    { .script_first = 97, .script_count = 1, .family_first = 71, .family_count = 1 },
    { .script_first = 98, .script_count = 1, .family_first = 72, .family_count = 1 },
    { .script_first = 99, .script_count = 1, .family_first = 73, .family_count = 1 },
    { .script_first = 100, .script_count = 1, .family_first = 74, .family_count = 1 },
    { .script_first = 101, .script_count = 1, .family_first = 75, .family_count = 1 },
    { .script_first = 102, .script_count = 1, .family_first = 76, .family_count = 1 },
    { .script_first = 103, .script_count = 1, .family_first = 77, .family_count = 1 },
    { .script_first = 104, .script_count = 1, .family_first = 78, .family_count = 1 },
    { .script_first = 105, .script_count = 1, .family_first = 79, .family_count = 1 },
    { .script_first = 106, .script_count = 1, .family_first = 80, .family_count = 1 },
    { .script_first = 107, .script_count = 1, .family_first = 81, .family_count = 1 },
    { .script_first = 108, .script_count = 1, .family_first = 82, .family_count = 1 },
    { .script_first = 109, .script_count = 1, .family_first = 83, .family_count = 1 },
    { .script_first = 110, .script_count = 1, .family_first = 84, .family_count = 1 },
    { .script_first = 111, .script_count = 1, .family_first = 85, .family_count = 1 },
    { .script_first = 112, .script_count = 1, .family_first = 86, .family_count = 1 },
    { .script_first = 113, .script_count = 1, .family_first = 87, .family_count = 1 },
    { .script_first = 114, .script_count = 1, .family_first = 88, .family_count = 1 },
    { .script_first = 115, .script_count = 1, .family_first = 89, .family_count = 1 },
    { .script_first = 116, .script_count = 1, .family_first = 90, .family_count = 1 },
    { .script_first = 117, .script_count = 1, .family_first = 91, .family_count = 1 },
    { .script_first = 118, .script_count = 1, .family_first = 92, .family_count = 1 },
    { .script_first = 119, .script_count = 1, .family_first = 93, .family_count = 1 },
    { .script_first = 120, .script_count = 1, .family_first = 94, .family_count = 1 },
    { .script_first = 121, .script_count = 1, .family_first = 95, .family_count = 1 },
    { .script_first = 122, .script_count = 1, .family_first = 96, .family_count = 1 },
    { .script_first = 123, .script_count = 1, .family_first = 97, .family_count = 1 },
    { .script_first = 124, .script_count = 1, .family_first = 98, .family_count = 1 },
    { .script_first = 125, .script_count = 1, .family_first = 99, .family_count = 1 },
    { .script_first = 126, .script_count = 1, .family_first = 100, .family_count = 1 },
    { .script_first = 127, .script_count = 1, .family_first = 101, .family_count = 1 },
    { .script_first = 128, .script_count = 1, .family_first = 102, .family_count = 1 },
    { .script_first = 129, .script_count = 1, .family_first = 103, .family_count = 1 },
    { .script_first = 130, .script_count = 1, .family_first = 104, .family_count = 1 },
    { .script_first = 131, .script_count = 1, .family_first = 105, .family_count = 1 },
    { .script_first = 132, .script_count = 1, .family_first = 106, .family_count = 1 },
    { .script_first = 133, .script_count = 1, .family_first = 107, .family_count = 1 },
    { .script_first = 134, .script_count = 1, .family_first = 108, .family_count = 1 },
    { .script_first = 135, .script_count = 1, .family_first = 109, .family_count = 1 },
    { .script_first = 136, .script_count = 1, .family_first = 110, .family_count = 1 },
    { .script_first = 137, .script_count = 1, .family_first = 111, .family_count = 1 },
    { .script_first = 138, .script_count = 1, .family_first = 112, .family_count = 1 },
};
[[maybe_unused]] constexpr unsigned kWindowsCommonFallbackRuleCount = 96;
[[maybe_unused]] constexpr unsigned kWindowsCommonFallbackHeadFirst = 0;
[[maybe_unused]] constexpr unsigned kWindowsCommonFallbackHeadCount = 2;
[[maybe_unused]] constexpr unsigned kWindowsCommonFallbackTailFirst = 113;
[[maybe_unused]] constexpr unsigned kWindowsCommonFallbackTailCount = 7;

// modules/libpref/init/all.js, as MOZ_DEFAULT_PREFS data. Firefox parses
// the contents of that variable as default prefs, so cleartype/src/prefs.cpp
// hands it this and nothing has to be installed into a profile.
[[maybe_unused]] const auto* const kWindowsPrefs =
    "pref(\"gfx.font_rendering.freetype.gamma\", 180);\n"
    "pref(\"gfx.font_rendering.freetype.enhanced_contrast\", 100);\n"
    // StaticPrefList.yaml gives the picture cache 512-wide tiles under XP_WIN
    // and 1024-wide ones everywhere else. Text on a tile seam blends a level
    // away from the same text inside a tile, so the seams have to fall in the
    // same columns.
    "pref(\"gfx.webrender.picture-tile-width\", 512);\n"
    "pref(\"widget.non-native-theme.use-theme-accent\", false);\n"
    "pref(\"font.name-list.serif.x-math\", \"Latin Modern Math, STIX Two Math, XITS Math, Cambria Math, Libertinus Math, DejaVu Math TeX Gyre, TeX Gyre Bonum Math, TeX Gyre Pagella Math, TeX Gyre Schola, TeX Gyre Termes Math, STIX Math, Asana Math, STIXGeneral, DejaVu Serif, DejaVu Sans, Times New Roman\");\n"
    "pref(\"font.name-list.sans-serif.x-math\", \"Arial\");\n"
    "pref(\"font.name-list.monospace.x-math\", \"Consolas\");\n"
    "pref(\"font.size.monospace.ar\", 13);\n"
    "pref(\"font.size.monospace.el\", 13);\n"
    "pref(\"font.size.monospace.he\", 13);\n"
    "pref(\"font.minimum-size.th\", 10);\n"
    "pref(\"font.size.monospace.x-cyrillic\", 13);\n"
    "pref(\"font.default.x-devanagari\", \"sans-serif\");\n"
    "pref(\"font.size.monospace.x-unicode\", 13);\n"
    "pref(\"font.size.monospace.x-western\", 13);\n"
    "pref(\"font.name-list.emoji\", \"Segoe UI Emoji, Twemoji Mozilla\");\n"
    "pref(\"font.name-list.serif.ar\", \"Times New Roman\");\n"
    "pref(\"font.name-list.sans-serif.ar\", \"Segoe UI, Tahoma, Arial\");\n"
    "pref(\"font.name-list.monospace.ar\", \"Consolas\");\n"
    "pref(\"font.name-list.cursive.ar\", \"Comic Sans MS\");\n"
    "pref(\"font.name-list.serif.el\", \"Times New Roman\");\n"
    "pref(\"font.name-list.sans-serif.el\", \"Arial\");\n"
    "pref(\"font.name-list.monospace.el\", \"Consolas\");\n"
    "pref(\"font.name-list.cursive.el\", \"Comic Sans MS\");\n"
    "pref(\"font.name-list.serif.he\", \"Narkisim, David\");\n"
    "pref(\"font.name-list.sans-serif.he\", \"Arial\");\n"
    "pref(\"font.name-list.monospace.he\", \"Fixed Miriam Transparent, Miriam Fixed, Rod, Consolas, Courier New\");\n"
    "pref(\"font.name-list.cursive.he\", \"Guttman Yad, Ktav, Arial\");\n"
    "pref(\"font.name-list.serif.ja\", \"Yu Mincho, MS PMincho, MS Mincho, Noto Serif CJK JP, Noto Serif JP, Meiryo, Yu Gothic, MS PGothic, MS Gothic\");\n"
    "pref(\"font.name-list.sans-serif.ja\", \"Meiryo, Yu Gothic, MS PGothic, MS Gothic, Noto Sans CJK JP, Noto Sans JP\");\n"
    "pref(\"font.name-list.monospace.ja\", \"BIZ UDGothic, MS Gothic, MS Mincho, Meiryo, Yu Gothic, Yu Mincho\");\n"
    "pref(\"font.name-list.serif.ko\", \"Batang, Noto Serif CJK KR, Noto Serif KR, Gulim\");\n"
    "pref(\"font.name-list.sans-serif.ko\", \"Malgun Gothic, Gulim, Noto Sans CJK KR, Noto Sans KR\");\n"
    "pref(\"font.name-list.monospace.ko\", \"GulimChe\");\n"
    "pref(\"font.name-list.cursive.ko\", \"Gungsuh\");\n"
    "pref(\"font.name-list.serif.th\", \"Tahoma\");\n"
    "pref(\"font.name-list.sans-serif.th\", \"Tahoma\");\n"
    "pref(\"font.name-list.monospace.th\", \"Tahoma\");\n"
    "pref(\"font.name-list.cursive.th\", \"Tahoma\");\n"
    "pref(\"font.name-list.serif.x-cyrillic\", \"Times New Roman\");\n"
    "pref(\"font.name-list.sans-serif.x-cyrillic\", \"Arial\");\n"
    "pref(\"font.name-list.monospace.x-cyrillic\", \"Consolas\");\n"
    "pref(\"font.name-list.cursive.x-cyrillic\", \"Comic Sans MS\");\n"
    "pref(\"font.name-list.serif.x-unicode\", \"Times New Roman\");\n"
    "pref(\"font.name-list.sans-serif.x-unicode\", \"Arial\");\n"
    "pref(\"font.name-list.monospace.x-unicode\", \"Consolas\");\n"
    "pref(\"font.name-list.cursive.x-unicode\", \"Comic Sans MS\");\n"
    "pref(\"font.name-list.serif.x-western\", \"Times New Roman\");\n"
    "pref(\"font.name-list.sans-serif.x-western\", \"Arial\");\n"
    "pref(\"font.name-list.monospace.x-western\", \"Consolas\");\n"
    "pref(\"font.name-list.cursive.x-western\", \"Comic Sans MS\");\n"
    "pref(\"font.name-list.serif.zh-CN\", \"SimSun, MS Song, SimSun-ExtB, Noto Serif CJK SC, Noto Serif SC\");\n"
    "pref(\"font.name-list.sans-serif.zh-CN\", \"Microsoft YaHei, SimHei, Noto Sans CJK SC, Noto Sans SC\");\n"
    "pref(\"font.name-list.monospace.zh-CN\", \"NSimSun, SimSun, MS Song, SimSun-ExtB\");\n"
    "pref(\"font.name-list.cursive.zh-CN\", \"KaiTi, KaiTi_GB2312\");\n"
    "pref(\"font.name-list.serif.zh-TW\", \"Times New Roman, PMingLiu, MingLiU, MingLiU-ExtB, Noto Serif CJK TC, Noto Serif TC\");\n"
    "pref(\"font.name-list.sans-serif.zh-TW\", \"Arial, Microsoft JhengHei, PMingLiU, MingLiU, MingLiU-ExtB, Noto Sans CJK TC, Noto Sans TC\");\n"
    "pref(\"font.name-list.monospace.zh-TW\", \"MingLiU, MingLiU-ExtB\");\n"
    "pref(\"font.name-list.cursive.zh-TW\", \"DFKai-SB\");\n"
    "pref(\"font.name-list.serif.zh-HK\", \"Times New Roman, MingLiu_HKSCS, Ming(for ISO10646), MingLiU, MingLiU_HKSCS-ExtB, Noto Serif CJK HK, Noto Serif HK, Microsoft JhengHei\");\n"
    "pref(\"font.name-list.sans-serif.zh-HK\", \"Arial, MingLiU_HKSCS, Ming(for ISO10646), MingLiU, MingLiU_HKSCS-ExtB, Microsoft JhengHei, Noto Sans CJK HK, Noto Sans HK\");\n"
    "pref(\"font.name-list.monospace.zh-HK\", \"MingLiU_HKSCS, Ming(for ISO10646), MingLiU, MingLiU_HKSCS-ExtB, Microsoft JhengHei\");\n"
    "pref(\"font.name-list.cursive.zh-HK\", \"DFKai-SB\");\n"
    "pref(\"font.name-list.serif.x-devanagari\", \"Kokila, Raghindi\");\n"
    "pref(\"font.name-list.sans-serif.x-devanagari\", \"Nirmala UI, Mangal\");\n"
    "pref(\"font.name-list.monospace.x-devanagari\", \"Mangal, Nirmala UI\");\n"
    "pref(\"font.name-list.serif.x-tamil\", \"Latha\");\n"
    "pref(\"font.name-list.monospace.x-tamil\", \"Latha\");\n"
    "pref(\"font.name-list.serif.x-armn\", \"Sylfaen\");\n"
    "pref(\"font.name-list.sans-serif.x-armn\", \"Arial AMU\");\n"
    "pref(\"font.name-list.monospace.x-armn\", \"Arial AMU\");\n"
    "pref(\"font.name-list.serif.x-beng\", \"Vrinda, Akaash, Likhan, Ekushey Punarbhaba\");\n"
    "pref(\"font.name-list.sans-serif.x-beng\", \"Nirmala Text, Vrinda, Akaash, Likhan, Ekushey Punarbhaba\");\n"
    "pref(\"font.name-list.monospace.x-beng\", \"Mitra Mono, Likhan, Mukti Narrow\");\n"
    "pref(\"font.name-list.serif.x-cans\", \"Aboriginal Serif, BJCree Uni\");\n"
    "pref(\"font.name-list.sans-serif.x-cans\", \"Aboriginal Sans\");\n"
    "pref(\"font.name-list.monospace.x-cans\", \"Aboriginal Sans, OskiDakelh, Pigiarniq, Uqammaq\");\n"
    "pref(\"font.name-list.serif.x-ethi\", \"Visual Geez Unicode, Visual Geez Unicode Agazian\");\n"
    "pref(\"font.name-list.sans-serif.x-ethi\", \"GF Zemen Unicode\");\n"
    "pref(\"font.name-list.monospace.x-ethi\", \"Ethiopia Jiret\");\n"
    "pref(\"font.name-list.cursive.x-ethi\", \"Visual Geez Unicode Title\");\n"
    "pref(\"font.name-list.serif.x-geor\", \"Sylfaen, BPG Paata Khutsuri U, TITUS Cyberbit Basic\");\n"
    "pref(\"font.name-list.sans-serif.x-geor\", \"BPG Classic 99U\");\n"
    "pref(\"font.name-list.monospace.x-geor\", \"BPG Classic 99U\");\n"
    "pref(\"font.name-list.serif.x-gujr\", \"Shruti\");\n"
    "pref(\"font.name-list.sans-serif.x-gujr\", \"Shruti\");\n"
    "pref(\"font.name-list.monospace.x-gujr\", \"Shruti\");\n"
    "pref(\"font.name-list.serif.x-guru\", \"Raavi, Saab\");\n"
    "pref(\"font.name-list.sans-serif.x-guru\", \",\");\n"
    "pref(\"font.name-list.monospace.x-guru\", \"Raavi, Saab\");\n"
    "pref(\"font.name-list.serif.x-khmr\", \"PhnomPenh OT,.Mondulkiri U GR 1.5, Khmer OS\");\n"
    "pref(\"font.name-list.sans-serif.x-khmr\", \"Khmer OS\");\n"
    "pref(\"font.name-list.monospace.x-khmr\", \"Khmer OS, Khmer OS System\");\n"
    "pref(\"font.name-list.serif.x-mlym\", \"Rachana_w01, AnjaliOldLipi, Kartika, ThoolikaUnicode\");\n"
    "pref(\"font.name-list.sans-serif.x-mlym\", \"Rachana_w01, AnjaliOldLipi, Kartika, ThoolikaUnicode\");\n"
    "pref(\"font.name-list.monospace.x-mlym\", \"Rachana_w01, AnjaliOldLipi, Kartika, ThoolikaUnicode\");\n"
    "pref(\"font.name-list.serif.x-orya\", \"ori1Uni, Kalinga\");\n"
    "pref(\"font.name-list.sans-serif.x-orya\", \"ori1Uni, Kalinga\");\n"
    "pref(\"font.name-list.monospace.x-orya\", \"ori1Uni, Kalinga\");\n"
    "pref(\"font.name-list.serif.x-telu\", \"Gautami, Akshar Unicode\");\n"
    "pref(\"font.name-list.sans-serif.x-telu\", \"Gautami, Akshar Unicode\");\n"
    "pref(\"font.name-list.monospace.x-telu\", \"Gautami, Akshar Unicode\");\n"
    "pref(\"font.name-list.serif.x-knda\", \"Tunga, AksharUnicode\");\n"
    "pref(\"font.name-list.sans-serif.x-knda\", \"Tunga, AksharUnicode\");\n"
    "pref(\"font.name-list.monospace.x-knda\", \"Tunga, AksharUnicode\");\n"
    "pref(\"font.name-list.serif.x-sinh\", \"Iskoola Pota, AksharUnicode\");\n"
    "pref(\"font.name-list.sans-serif.x-sinh\", \"Iskoola Pota, AksharUnicode\");\n"
    "pref(\"font.name-list.monospace.x-sinh\", \"Iskoola Pota, AksharUnicode\");\n"
    "pref(\"font.name-list.serif.x-tibt\", \"Tibetan Machine Uni, Jomolhari, Microsoft Himalaya\");\n"
    "pref(\"font.name-list.sans-serif.x-tibt\", \"Tibetan Machine Uni, Jomolhari, Microsoft Himalaya\");\n"
    "pref(\"font.name-list.monospace.x-tibt\", \"Tibetan Machine Uni, Jomolhari, Microsoft Himalaya\");\n"
    "pref(\"font.name-list.cursive.x-math\", \"Comic Sans MS\");\n"
    "pref(\"font.name-list.cursive.ja\", \",\");\n"
    "pref(\"font.name-list.cursive.x-armn\", \",\");\n"
    "pref(\"font.name-list.cursive.x-beng\", \",\");\n"
    "pref(\"font.name-list.cursive.x-cans\", \",\");\n"
    "pref(\"font.name-list.cursive.x-devanagari\", \",\");\n"
    "pref(\"font.name-list.cursive.x-geor\", \",\");\n"
    "pref(\"font.name-list.cursive.x-gujr\", \",\");\n"
    "pref(\"font.name-list.cursive.x-guru\", \",\");\n"
    "pref(\"font.name-list.cursive.x-khmr\", \",\");\n"
    "pref(\"font.name-list.cursive.x-knda\", \",\");\n"
    "pref(\"font.name-list.cursive.x-mlym\", \",\");\n"
    "pref(\"font.name-list.cursive.x-orya\", \",\");\n"
    "pref(\"font.name-list.cursive.x-sinh\", \",\");\n"
    "pref(\"font.name-list.sans-serif.x-tamil\", \",\");\n"
    "pref(\"font.name-list.cursive.x-tamil\", \",\");\n"
    "pref(\"font.name-list.cursive.x-telu\", \",\");\n"
    "pref(\"font.name-list.cursive.x-tibt\", \",\");\n"
    "pref(\"ui.font.caption\", \"Segoe UI\");\n"
    "pref(\"ui.font.caption.size\", \"12\");\n"
    "pref(\"ui.font.caption.weight\", \"400\");\n"
    "pref(\"ui.font.caption.italic\", false);\n"
    "pref(\"ui.font.icon\", \"Segoe UI\");\n"
    "pref(\"ui.font.icon.size\", \"12\");\n"
    "pref(\"ui.font.icon.weight\", \"400\");\n"
    "pref(\"ui.font.icon.italic\", false);\n"
    "pref(\"ui.font.menu\", \"Segoe UI\");\n"
    "pref(\"ui.font.menu.size\", \"12\");\n"
    "pref(\"ui.font.menu.weight\", \"400\");\n"
    "pref(\"ui.font.menu.italic\", false);\n"
    "pref(\"ui.font.message-box\", \"Segoe UI\");\n"
    "pref(\"ui.font.message-box.size\", \"12\");\n"
    "pref(\"ui.font.message-box.weight\", \"400\");\n"
    "pref(\"ui.font.message-box.italic\", false);\n"
    "pref(\"ui.font.small-caption\", \"Segoe UI\");\n"
    "pref(\"ui.font.small-caption.size\", \"12\");\n"
    "pref(\"ui.font.small-caption.weight\", \"400\");\n"
    "pref(\"ui.font.small-caption.italic\", false);\n"
    "pref(\"ui.font.status-bar\", \"Segoe UI\");\n"
    "pref(\"ui.font.status-bar.size\", \"12\");\n"
    "pref(\"ui.font.status-bar.weight\", \"400\");\n"
    "pref(\"ui.font.status-bar.italic\", false);\n"
    "pref(\"ui.font.-moz-pull-down-menu\", \"Segoe UI\");\n"
    "pref(\"ui.font.-moz-pull-down-menu.size\", \"12\");\n"
    "pref(\"ui.font.-moz-pull-down-menu.weight\", \"400\");\n"
    "pref(\"ui.font.-moz-pull-down-menu.italic\", false);\n"
    "pref(\"ui.font.-moz-button\", \"MS Shell Dlg 2\");\n"
    "pref(\"ui.font.-moz-button.size\", \"12\");\n"
    "pref(\"ui.font.-moz-button.weight\", \"400\");\n"
    "pref(\"ui.font.-moz-button.italic\", false);\n"
    "pref(\"ui.font.-moz-list\", \"MS Shell Dlg 2\");\n"
    "pref(\"ui.font.-moz-list.size\", \"12\");\n"
    "pref(\"ui.font.-moz-list.weight\", \"400\");\n"
    "pref(\"ui.font.-moz-list.italic\", false);\n"
    "pref(\"ui.font.-moz-field\", \"MS Shell Dlg 2\");\n"
    "pref(\"ui.font.-moz-field.size\", \"12\");\n"
    "pref(\"ui.font.-moz-field.weight\", \"400\");\n"
    "pref(\"ui.font.-moz-field.italic\", false);\n"
    ;


// gfx/thebes/StandardFonts-win10.inc kFontSubstitutes, the table
// gfxDWriteFontList::GetFontSubstitutes loads before it reads the registry's
// own HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes.
// gfxDWriteFontList::FindAndAddFamiliesLocked rewrites the key name through it
// before any family lookup, so the answer never depends on the language.
// gfxFcPlatformFontList has no such step and hands the name to fontconfig,
// whose answer for "Times" under lang=hy is Sylfaen where Windows has Times
// New Roman.
struct FontSubstitute
{
    const char* substitute;
    const char* actual;
};

inline constexpr FontSubstitute kFontSubstitutes[] = {
    { "Arabic Transparent", "Arial" },
    { "Arial Baltic", "Arial" },
    { "Arial CE", "Arial" },
    { "Arial CYR", "Arial" },
    { "Arial Greek", "Arial" },
    { "Arial TUR", "Arial" },
    { "Courier New Baltic", "Courier New" },
    { "Courier New CE", "Courier New" },
    { "Courier New CYR", "Courier New" },
    { "Courier New Greek", "Courier New" },
    { "Courier New TUR", "Courier New" },
    { "Helv", "Microsoft Sans Serif" },
    { "Helvetica", "Arial" },
    { "MS Shell Dlg 2", "Tahoma" },
    { "Tahoma Armenian", "Tahoma" },
    { "Times", "Times New Roman" },
    { "Times New Roman Baltic", "Times New Roman" },
    { "Times New Roman CE", "Times New Roman" },
    { "Times New Roman CYR", "Times New Roman" },
    { "Times New Roman Greek", "Times New Roman" },
    { "Times New Roman TUR", "Times New Roman" },
    { "Tms Rmn", "Times New Roman" },
    { "MS Shell Dlg", "Microsoft Sans Serif" },
    { "Arial (Arabic)", "Arial" },
    { "Courier New (Arabic)", "Courier New" },
    { "Times New Roman (Arabic)", "Times New Roman" },
    { "Courier", "Courier New" },
    { "Fixedsys Greek", "Fixedsys" },
    { "MS Serif Greek", "Times New Roman" },
    { "MS Sans Serif Greek", "Microsoft Sans Serif" },
    { "Small Fonts Greek", "Arial" },
    { "System Greek", "System" },
    { "Arial (Hebrew)", "Arial" },
    { "Courier New (Hebrew)", "Courier New" },
    { "David Transparent", "David" },
    { "Fixed Miriam Transparent", "Miriam Fixed" },
    { "Miriam Transparent", "Miriam" },
    { "Rod Transparent", "Rod" },
    { "Times New Roman (Hebrew)", "Times New Roman" },
    { "\u6a19\u6e96\u660e\u671d", "\uff2d\uff33 \u660e\u671d" },
    { "\u6a19\u6e96\u30b4\u30b7\u30c3\u30af", "\uff2d\uff33 \u30b4\u30b7\u30c3\u30af" },
    { "\u30b4\u30b7\u30c3\u30af", "\uff2d\uff33 \u30b4\u30b7\u30c3\u30af" },
    { "\uff7a\uff9e\uff7c\uff6f\uff78", "\uff2d\uff33 \u30b4\u30b7\u30c3\u30af" },
    { "\uff78\uff70\uff98\uff74", "Courier New" },
    { "\uff80\uff72\uff91\uff7d\uff9e\uff9b\uff8f\uff9d", "Times New Roman" },
    { "\uff8d\uff99\uff8d\uff9e\uff81\uff76", "Arial" },
    { "FangSong_GB2312", "FangSong" },
    { "KaiTi_GB2312", "KaiTi" },
};

}  // namespace firefox_parity

#endif  // FIREFOX_PARITY_DATA_H_INCLUDED
