//+--------------------------------------------------------------------------
//
//  basetsd.h - mirrored from the Windows SDK (shared/basetsd.h).
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Only the declarations the DirectWrite headers need are reproduced here;
//  the SDK originals are far larger. Types with no source in this SDK subset
//  (GUID, HRESULT) and anything that has to differ off-Windows live in
//  compat.h instead.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_BASETSD_H
#define DWC_MIRROR_BASETSD_H
#pragma once

#include "compat.h"

// Vendor text. Drift from the SDK is caught by diffing include/ against
// third_party/, never by static analysis noticing Microsoft's house style.
// NOLINTBEGIN


/* --- INT8 --- */
typedef signed char         INT8, *PINT8;


/* --- INT16 --- */
typedef signed short        INT16, *PINT16;


/* --- INT32 --- */
typedef signed int          INT32, *PINT32;


/* --- INT64 --- */
typedef signed __int64      INT64, *PINT64;


/* --- UINT8 --- */
typedef unsigned char       UINT8, *PUINT8;


/* --- UINT16 --- */
typedef unsigned short      UINT16, *PUINT16;


/* --- UINT32 --- */
typedef unsigned int        UINT32, *PUINT32;


/* --- UINT64 --- */
typedef unsigned __int64    UINT64, *PUINT64;


// NOLINTEND


#endif // DWC_MIRROR_BASETSD_H
