//+--------------------------------------------------------------------------
//
//  d2dbasetypes.h - mirrored from the Windows SDK (um/d2dbasetypes.h).
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Only the declarations the DirectWrite headers need are reproduced here;
//  the SDK originals are far larger. Types with no source in this SDK subset
//  (GUID, HRESULT) and anything that has to differ off-Windows live in
//  compat.h instead.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_D2DBASETYPES_H
#define DWC_MIRROR_D2DBASETYPES_H
#pragma once

#include "compat.h"

// Vendor text. Drift from the SDK is caught by diffing include/ against
// third_party/, never by static analysis noticing Microsoft's house style.
// NOLINTBEGIN


/* --- D2D_COLOR_F --- */
typedef D3DCOLORVALUE D2D_COLOR_F;


// NOLINTEND


#endif // DWC_MIRROR_D2DBASETYPES_H
