//+--------------------------------------------------------------------------
//
//  d3d9types.h - mirrored from the Windows SDK (shared/d3d9types.h).
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Only the declarations the DirectWrite headers need are reproduced here;
//  the SDK originals are far larger. Types with no source in this SDK subset
//  (GUID, HRESULT) and anything that has to differ off-Windows live in
//  compat.h instead.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_D3D9TYPES_H
#define DWC_MIRROR_D3D9TYPES_H
#pragma once

#include "compat.h"

// Vendor text. Drift from the SDK is caught by diffing include/ against
// third_party/, never by static analysis noticing Microsoft's house style.
// NOLINTBEGIN


#ifndef D3DCOLORVALUE_DEFINED


/* --- D3DCOLORVALUE --- */
typedef struct _D3DCOLORVALUE {
    float r;
    float g;
    float b;
    float a;
} D3DCOLORVALUE;


#define D3DCOLORVALUE_DEFINED
#endif // D3DCOLORVALUE_DEFINED


// NOLINTEND


#endif // DWC_MIRROR_D3D9TYPES_H
