//+--------------------------------------------------------------------------
//
//  dwrite_core_iids.h - IID associations for the interfaces in dwrite_core.h.
//
//  GENERATED by tools/mirror_headers.py - do not edit by hand.
//
//  DWriteCore's QueryInterface parses these IIDs from ASCII string literals
//  at runtime (confirmed in libdwritecore.so at 0x251a00), so the values
//  below were cross-checked against the string table in the binary.
//
//----------------------------------------------------------------------------

#ifndef DWRITE_CORE_IIDS_H_INCLUDED
#define DWRITE_CORE_IIDS_H_INCLUDED
#pragma once

#include "compat.h"

#ifdef __cplusplus

DWRITE_DEFINE_IID(IDWriteEventSink, 0xB2839DC9, 0x5419, 0x4223, 0xA0, 0x69, 0xC7, 0x92, 0xD2, 0xDC, 0x6B, 0xA0)

#endif // __cplusplus

#endif // DWRITE_CORE_IIDS_H_INCLUDED
