//+--------------------------------------------------------------------------
//
//  dwrite_experimental_iids.h - IID associations for the interfaces in DWriteExperimental.h.
//
//  GENERATED by tools/mirror_headers.py - do not edit by hand.
//
//  DWriteCore's QueryInterface parses these IIDs from ASCII string literals
//  at runtime (confirmed in libdwritecore.so at 0x251a00), so the values
//  below were cross-checked against the string table in the binary.
//
//----------------------------------------------------------------------------

#ifndef DWRITE_EXPERIMENTAL_IIDS_H_INCLUDED
#define DWRITE_EXPERIMENTAL_IIDS_H_INCLUDED
#pragma once

#include "compat.h"

#ifdef __cplusplus

DWRITE_DEFINE_IID(IDWriteAsyncResult1, 0xC50F19A9, 0xB4EC, 0x47DB, 0x9A, 0x66, 0xC3, 0x08, 0xC1, 0xE0, 0x04, 0x5F)
DWRITE_DEFINE_IID(IDWriteFileDownload, 0xFAC87BFA, 0xB85A, 0x4FEA, 0x9F, 0xD5, 0xD0, 0x60, 0x96, 0x2C, 0x29, 0x7C)
DWRITE_DEFINE_IID(IDWriteFileDownloadList, 0x8AB33F0B, 0x6724, 0x47C6, 0xA4, 0x81, 0x93, 0xB3, 0x3A, 0xED, 0x64, 0x78)
DWRITE_DEFINE_IID(IDWriteFontDownloadQueue1, 0x96E1C125, 0x3AB4, 0x4728, 0xAA, 0xBA, 0xE3, 0xC9, 0x19, 0xB7, 0xF0, 0xD0)

#endif // __cplusplus

#endif // DWRITE_EXPERIMENTAL_IIDS_H_INCLUDED
