//+--------------------------------------------------------------------------
//
//  rpc.h - mirrored from the Windows SDK (shared/rpc.h).
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Only the declarations the DirectWrite headers need are reproduced here;
//  the SDK originals are far larger. Types with no source in this SDK subset
//  (GUID, HRESULT) and anything that has to differ off-Windows live in
//  compat.h instead.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_RPC_H
#define DWC_MIRROR_RPC_H
#pragma once

#include "compat.h"

// Vendor text. Drift from the SDK is caught by diffing include/ against
// third_party/, never by static analysis noticing Microsoft's house style.
// NOLINTBEGIN


/* --- __RPC_API --- */
#if !defined(__RPC_MAC__) && ( (_MSC_VER >= 800) || defined(_STDCALL_SUPPORTED) )
#	define __RPC_API  __stdcall
#	define __RPC_USER __stdcall
#	define __RPC_STUB __stdcall
#	define  RPC_ENTRY __stdcall
#else // Not Win32/Win64
#	define __RPC_API
#	define __RPC_USER
#	define __RPC_STUB
#	define RPC_ENTRY
#endif


/* --- __RPC_USER --- */
#if !defined(__RPC_MAC__) && ( (_MSC_VER >= 800) || defined(_STDCALL_SUPPORTED) )
#	define __RPC_API  __stdcall
#	define __RPC_USER __stdcall
#	define __RPC_STUB __stdcall
#	define  RPC_ENTRY __stdcall
#else // Not Win32/Win64
#	define __RPC_API
#	define __RPC_USER
#	define __RPC_STUB
#	define RPC_ENTRY
#endif


/* --- __RPC_STUB --- */
#if !defined(__RPC_MAC__) && ( (_MSC_VER >= 800) || defined(_STDCALL_SUPPORTED) )
#	define __RPC_API  __stdcall
#	define __RPC_USER __stdcall
#	define __RPC_STUB __stdcall
#	define  RPC_ENTRY __stdcall
#else // Not Win32/Win64
#	define __RPC_API
#	define __RPC_USER
#	define __RPC_STUB
#	define RPC_ENTRY
#endif


/* --- __RPC_FAR --- */
#define __RPC_FAR


// NOLINTEND


#endif // DWC_MIRROR_RPC_H
