//+--------------------------------------------------------------------------
//
//  rpcsal.h - mirrored from the Windows SDK (shared/rpcsal.h).
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Only the declarations the DirectWrite headers need are reproduced here;
//  the SDK originals are far larger. Types with no source in this SDK subset
//  (GUID, HRESULT) and anything that has to differ off-Windows live in
//  compat.h instead.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_RPCSAL_H
#define DWC_MIRROR_RPCSAL_H
#pragma once

#include "compat.h"

// Vendor text. Drift from the SDK is caught by diffing include/ against
// third_party/, never by static analysis noticing Microsoft's house style.
// NOLINTBEGIN


/* --- __RPC__in --- */
#define __RPC__in                                    _SAL1_2_Source_(__RPC__in, (), _Pre_ _Notref_ _Notnull_ _Pre_ _Valid_)


/* --- __RPC__out --- */
#define __RPC__out                                   _SAL1_2_Source_(__RPC__out, (), _Out_)


/* --- __RPC__deref_out --- */
#define __RPC__deref_out                             _SAL1_2_Source_(__RPC__deref_out, (), _Outptr_)


/* --- __RPC__deref_out_opt --- */
#define __RPC__deref_out_opt                        _SAL1_2_Source_(__RPC__deref_out_opt, (), __RPC__deref_out)


// NOLINTEND


#endif // DWC_MIRROR_RPCSAL_H
