//+--------------------------------------------------------------------------
//
//  specstrings.h - SAL annotations for the DirectWrite headers.
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Extracted from shared/no_sal2.h, the SDK's own set of no-op SAL
//  definitions. These annotations drive static analysis only and have
//  no ABI effect; without _PREFAST_ the real SDK also compiles them
//  away. Using the SDK's own no-op forms keeps the arities right.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_SPECSTRINGS_H
#define DWC_MIRROR_SPECSTRINGS_H
#pragma once

#if defined(_WIN32)
#include <specstrings.h>
#else

// Vendor text. Drift from the SDK is caught by diffing include/
// against third_party/, never by static analysis.
// NOLINTBEGIN

#define _Analysis_assume_
#define _COM_Outptr_
#define _COM_Outptr_result_maybenull_
#define _Field_size_(s)
#define _Field_size_bytes_(s)
#define _Field_size_opt_(s)
#define _In_
#define _In_opt_
#define _In_opt_z_
#define _In_reads_(s)
#define _In_reads_bytes_(s)
#define _In_reads_opt_(s)
#define _In_z_
#define _Inout_
#define _Inout_updates_(s)
#define _Maybenull_
#define _Notnull_
#define _Null_terminated_
#define _Out_
#define _Out_opt_
#define _Out_range_(l,h)
#define _Out_writes_(s)
#define _Out_writes_bytes_(s)
#define _Out_writes_opt_(s)
#define _Out_writes_to_(s,c)
#define _Out_writes_to_opt_(s,c)
#define _Out_writes_z_(s)
#define _Outptr_
#define _Outptr_result_buffer_(s)
#define _Outptr_result_bytebuffer_(s)
#define _Outptr_result_maybenull_
#define _Outptr_result_z_
#define _Post_equal_to_(e)
#define _Post_satisfies_(e)
#define _Pre_
#define _Success_(c)
#define _Use_decl_annotations_
#define _Valid_

/* Declared only in sal.h, whose macro chains are not part of
   this SDK subset. Annotation-only, so a no-op is equivalent. */
#define _Field_z_
#define _MPPC_
#define _Notref_
#define _SAL1_2_Source_

#endif // !_WIN32

// NOLINTEND

#endif // DWC_MIRROR_SPECSTRINGS_H
