//+--------------------------------------------------------------------------
//
//  unknwn.h - mirrored from the Windows SDK (um/Unknwn.h).
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Only the declarations the DirectWrite headers need are reproduced here;
//  the SDK originals are far larger. Types with no source in this SDK subset
//  (GUID, HRESULT) and anything that has to differ off-Windows live in
//  compat.h instead.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_UNKNWN_H
#define DWC_MIRROR_UNKNWN_H
#pragma once

#include "compat.h"

// Vendor text. Drift from the SDK is caught by diffing include/ against
// third_party/, never by static analysis noticing Microsoft's house style.
// NOLINTBEGIN


#ifndef __IUnknown_INTERFACE_DEFINED__
#define __IUnknown_INTERFACE_DEFINED__


/* --- IUnknown --- */
MIDL_INTERFACE("00000000-0000-0000-C000-000000000046")
        IUnknown
        {
        public:
            BEGIN_INTERFACE
            virtual HRESULT STDMETHODCALLTYPE QueryInterface(
                           REFIID riid,
                                    _COM_Outptr_ void __RPC_FAR *__RPC_FAR *ppvObject) = 0;

            virtual ULONG STDMETHODCALLTYPE AddRef( void) = 0;

            virtual ULONG STDMETHODCALLTYPE Release( void) = 0;

            template<class Q>
            HRESULT
#ifdef _M_CEE_PURE
            __clrcall
#else
            STDMETHODCALLTYPE
#endif
            QueryInterface(_COM_Outptr_ Q** pp)
            {
                return QueryInterface(__uuidof(Q), (void **)pp);
            }

            END_INTERFACE
        };


#endif // __IUnknown_INTERFACE_DEFINED__


// NOLINTEND


#endif // DWC_MIRROR_UNKNWN_H
