//+--------------------------------------------------------------------------
//
//  windef.h - mirrored from the Windows SDK (shared/windef.h).
//
//  GENERATED by tools/mirror_sdk_headers.py - do not edit by hand.
//
//  Only the declarations the DirectWrite headers need are reproduced here;
//  the SDK originals are far larger. Types with no source in this SDK subset
//  (GUID, HRESULT) and anything that has to differ off-Windows live in
//  compat.h instead.
//
//----------------------------------------------------------------------------

#ifndef DWC_MIRROR_WINDEF_H
#define DWC_MIRROR_WINDEF_H
#pragma once

#include "compat.h"

// Vendor text. Drift from the SDK is caught by diffing include/ against
// third_party/, never by static analysis noticing Microsoft's house style.
// NOLINTBEGIN


/* --- RECT --- */
typedef struct tagRECT
{
    LONG    left;
    LONG    top;
    LONG    right;
    LONG    bottom;
} RECT, *PRECT, NEAR *NPRECT, FAR *LPRECT;


/* --- POINT --- */
typedef struct tagPOINT
{
    LONG  x;
    LONG  y;
} POINT, *PPOINT, NEAR *NPPOINT, FAR *LPPOINT;


/* --- SIZE --- */
typedef struct tagSIZE
{
    LONG        cx;
    LONG        cy;
} SIZE, *PSIZE, *LPSIZE;


/* --- HDC --- */
DECLARE_HANDLE(HDC);


/* --- HFONT --- */
DECLARE_HANDLE(HFONT);


/* --- HMONITOR --- */
DECLARE_HANDLE(HMONITOR);


/* --- HBITMAP --- */
DECLARE_HANDLE(HBITMAP);


/* --- HGDIOBJ --- */
DECLARE_HANDLE(HGDIOBJ);


/* --- COLORREF --- */
typedef DWORD   COLORREF;


// NOLINTEND


#endif // DWC_MIRROR_WINDEF_H
