#!/usr/bin/env python3
"""
Generate the factory proxy: src/factory_proxy.h and src/factory_proxy_forward.cpp.

The shipped libdwritecore.so cannot enumerate fonts. It imports open/read/stat
and mmap but no opendir, readdir, scandir or glob, so it can only open paths it
is handed - and GetSystemFontCollection consequently returns S_OK with zero
families on any platform whose host has not supplied a font list.

Everything downstream of that works: hand the same library font files through
CreateFontFileReference -> IDWriteFontSetBuilder1::AddFontFile -> CreateFontSet
-> CreateFontCollectionFromFontSet and it builds a real collection, resolves
family names, and creates font faces. So the missing piece is discovery alone,
and it can be supplied from outside.

This emits a proxy that DWriteCoreCreateFactory returns in place of the real
factory. It forwards every method, except the system-font getters, which answer
from a collection built out of fontconfig's font list - see src/system_fonts.cpp.

IDWriteFactory .. IDWriteFactory9 is a single inheritance chain, which is what
makes this tractable: one C++ class deriving from IDWriteFactory9 has one vtable
covering all 60 slots, and QueryInterface for any IDWriteFactoryN can return the
same pointer. The compiler lays that vtable out in declaration order, which is
the same property tests/vtable_test.cpp already checks for every interface.

Two files are emitted so that generated and hand-written code stay separate:
the class declaration, and the forwarding bodies. The overridden methods are
declared here but defined by hand in src/factory_proxy_overrides.cpp.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import gen_vtable_test as flat_api
from paths import INCLUDE as INC, SRC

CHAIN = ["IDWriteFactory"] + ["IDWriteFactory%d" % n for n in range(1, 10)]

HEADERS = ["dwrite.h", "dwrite_1.h", "dwrite_2.h", "dwrite_3.h",
           "dwrite_core.h", "DWriteExperimental.h"]

# (interface, method) pairs the proxy answers itself instead of forwarding.
#
# The GetSystemFont* family is the point of the exercise. CreateTextFormat is
# here for a less obvious reason: its fontCollection parameter is optional, and
# a caller passing null gets DWriteCore's own empty system collection, so text
# layout would still resolve no families however well GetSystemFontCollection
# answered. Substituting the collection there is the difference between the
# enumeration API working and text actually rendering.
#
# GetSystemFontFallback is here for the same reason as the rest: it is built
# from the system font set, so it is empty too. Its replacement needs per-script
# family preferences - which font to reach for when a run has no glyph - and
# those are measured data, not plumbing; see tools/gen_fallback_data.py.
OVERRIDES = {
    ("IDWriteFactory", "GetSystemFontCollection"),
    ("IDWriteFactory2", "GetSystemFontFallback"),
    ("IDWriteFactory", "CreateTextFormat"),
    ("IDWriteFactory3", "GetSystemFontSet"),
    ("IDWriteFactory3", "GetSystemFontCollection"),
    ("IDWriteFactory6", "GetSystemFontSet"),
    ("IDWriteFactory6", "GetSystemFontCollection"),
    ("IDWriteFactory6", "CreateTextFormat"),
    ("IDWriteFactory7", "GetSystemFontSet"),
    ("IDWriteFactory7", "GetSystemFontCollection"),
}

BANNER = "// GENERATED by tools/gen_factory_proxy.py - do not edit by hand.\n"


def collect():
    ifaces = []
    for name in HEADERS:
        path = os.path.join(INC, name)
        if os.path.exists(path):
            ifaces += flat_api.parse_header(path)
    by_name = {i["name"]: i for i in ifaces}
    missing = [n for n in CHAIN if n not in by_name]
    if missing:
        sys.exit("factory chain incomplete, missing: %s" % ", ".join(missing))
    return by_name


def const_param(decl, name):
    """`T* p` -> `T* const p`: top-level const, which is what the body wants
    and what the function's type ignores, so declaration and definition stay
    compatible either way."""
    m = re.search(r'(\b%s\b)\s*$' % re.escape(name), decl)
    if not m or not name:
        return decl
    return decl[:m.start(1)] + "const " + decl[m.start(1):]


def signature(method):
    return ", ".join(const_param(decl, name) for decl, name in method["params"])


def declared_signature(method):
    """The same parameters without the top-level const. A declaration does not
    carry it - the function's type is identical either way - so spelling it
    there says nothing, which is what CppConstParameterInDeclaration reports."""
    return ", ".join(decl for decl, _ in method["params"])


def arguments(method):
    return ", ".join(name for _, name in method["params"])


def main():
    by_name = collect()

    decls = []
    bodies = []
    overridden = 0
    for iface in CHAIN:
        methods = by_name[iface]["methods"]
        decls.append("    // ---- %s %s" % (iface, "-" * (56 - len(iface))))
        for m in methods:
            key = (iface, m["name"])
            mark = "  // overridden" if key in OVERRIDES else ""
            decls.append("    %s STDMETHODCALLTYPE %s(%s) override;%s"
                         % (m["ret"], m["name"], declared_signature(m), mark))
            if key in OVERRIDES:
                overridden += 1
                continue
            # Cast to the interface that *declared* the method before calling.
            # A derived IDWriteFactoryN that redeclares a name hides the base's
            # overloads. The SDK headers un-hide some of them by hand -
            # IDWriteFactory6 carries "using IDWriteFactory3::GetSystemFontSet;"
            # - but not all: nothing re-exposes IDWriteFactory2's
            # TranslateColorGlyphRun past IDWriteFactory4's, so that one does not
            # resolve through an IDWriteFactory9*. Casting every call, instead
            # of tracking which methods were rescued, keeps this independent of
            # a detail the next SDK revision may change. Dispatch stays virtual.
            bodies.append(
                "%s STDMETHODCALLTYPE FactoryProxy::%s(%s)\n"
                "{\n    return static_cast<%s*>(real_)->%s(%s);\n}\n"
                % (m["ret"], m["name"], signature(m), iface, m["name"], arguments(m)))

    header = [
        BANNER,
        "//\n"
        "// The proxy DWriteCoreCreateFactory hands out. Forwards everything to the\n"
        "// real factory except the system-font getters, which the shipped library\n"
        "// cannot answer because it has no way to enumerate fonts.\n"
        "//\n"
        "// Deriving from IDWriteFactory9 covers the whole chain: each IDWriteFactoryN\n"
        "// derives from its predecessor, so this one vtable carries every slot and\n"
        "// QueryInterface can return the same pointer for any of them.\n",
        "#ifndef DWRITECORE_FACTORY_PROXY_H_INCLUDED\n"
        "#define DWRITECORE_FACTORY_PROXY_H_INCLUDED\n",
        # dwrite_core.h then DWriteExperimental.h, the order dwritecore_flat.h\n
        # uses: dwrite_3.h alone leaves IDWriteAsyncResult undeclared.\n
        '#include "dwrite_core.h"\n#include "DWriteExperimental.h"\n',
        "\nnamespace dwc\n{\n",
        "class FactoryProxy : public IDWriteFactory9\n{\npublic:\n",
        "    // Takes ownership of one reference on `real`.\n"
        "    explicit FactoryProxy(IDWriteFactory9* real);\n",
        "    IDWriteFactory9* real() const { return real_; }\n",
        "    // IUnknown\n"
        "    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** object) override;\n"
        "    ULONG STDMETHODCALLTYPE AddRef() override;\n"
        "    ULONG STDMETHODCALLTYPE Release() override;\n",
        "\n".join(decls) + "\n",
        "\nprivate:\n"
        "    // Private and non-virtual. Non-virtual because a virtual destructor\n"
        "    // would append a slot to a vtable that has to match IDWriteFactory9's\n"
        "    // layout exactly. Private because the only legitimate destruction is\n"
        "    // `delete this` from Release(), which is inside the class.\n"
        "    ~FactoryProxy();\n\n"
        "    IDWriteFactory9* real_;\n"
        "    long refs_;\n"
        "    // Lazily built font set and its collection views. Opaque here; the\n"
        "    // type and everything that fills it live in src/system_fonts.cpp.\n"
        "    struct SystemFonts* fonts_;\n"
        "};\n",
        "\n}  // namespace dwc\n",
        "\n#endif  // DWRITECORE_FACTORY_PROXY_H_INCLUDED\n",
    ]
    header_path = os.path.join(SRC, "factory_proxy.h")
    open(header_path, "w").write("".join(header))

    body = [
        BANNER,
        "//\n// One forwarding definition per method the proxy does not answer itself.\n"
        "// The overridden ones are defined in src/factory_proxy_overrides.cpp.\n"
        "//\n"
        "// Most of the casts below are redundant. Which ones are load-bearing\n"
        "// depends on which hidden overloads the SDK headers happen to\n"
        "// re-expose, so none of them is dropped; see the note in the\n"
        "// generator. Analysis is told once here instead of at every call.\n\n"
        "// ReSharper disable CppRedundantCastExpression\n\n",
        '#include "factory_proxy.h"\n\nnamespace dwc\n{\n\n',
        "\n".join(bodies),
        "\n}  // namespace dwc\n",
    ]
    body_path = os.path.join(SRC, "factory_proxy_forward.cpp")
    open(body_path, "w").write("".join(body))

    total = sum(len(by_name[i]["methods"]) for i in CHAIN)
    print("Generating the factory proxy")
    print("  %-34s %d methods (%d forwarded, %d overridden)"
          % (os.path.basename(header_path), total, total - overridden, overridden))
    print("  %-34s %d slots including IUnknown"
          % (os.path.basename(body_path), total + 3))


if __name__ == "__main__":
    main()
