#!/usr/bin/env python3
"""
Generate src/fallback_data.cpp - the per-script fallback table.

GetSystemFontFallback is built from the system font set, so on this build it is
as empty as the collection was. Closing it needs one thing the shipped library
cannot supply: which Unicode ranges belong to which script. The family to reach
for is then whatever fontconfig resolves for that script's language, which is
this host's answer rather than another platform's.

The ranges are inlined below, so this tool reads nothing and depends on nothing
outside itself.

No font is named. libdwritecore.so stands in for DWriteCore on Linux, and a
Linux DirectWrite asked what should render Devanagari answers with what this
machine has. Preferring Windows' own families is a parity question that belongs
to libcleartype,
which overrides this in its Firefox parity mode from DirectWrite's own
extracted table (cleartype/src/dwrite_fallback_table.h).

The ranges are Unicode block constants. fontconfig cannot supply them:
FcLangGetCharSet returns an *orthography*, the characters needed to write a
language, which is far narrower than the script - Arabic is 36 codepoints that
way against 256 in the block, and a fallback keyed on the orthography would miss
every character outside it. So the ranges are hand-written, and checked: each
entry carries the representative codepoint its script was probed with, and
generation fails if that codepoint falls outside the ranges declared for it.

Three scripts get deliberate treatment:

  * Han is ambiguous. Simplified, Traditional and Japanese all claim
    U+4E00..U+9FFF and nothing in the codepoint distinguishes them - the same
    reason the probe could say nothing about CJK. So Han is one mapping, and
    Japanese and Korean get only their unambiguous blocks: kana and Hangul.
  * Latin is the base case, not a fallback, and gets no mapping at all.
  * "Any" is the catch-all, emitted last and covering the whole of Unicode, so
    a codepoint no other entry claims still resolves to something. Mathematical
    symbols fall into it.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from paths import SRC

# script label, fontconfig language, representative codepoint, ranges.
#
# The fontconfig language is what the mapping resolves through at run time:
# whatever covers that script here is what the fallback reaches for. "Any" has
# no language - it is a range, not a script - and so gets no mapping.
SCRIPTS = [
    ("Arabic", "ar", 0x0627,
     [(0x0600, 0x06FF), (0x0750, 0x077F), (0x08A0, 0x08FF), (0xFB50, 0xFDFF), (0xFE70, 0xFEFF)]),
    ("Greek", "el", 0x0391,
     [(0x0370, 0x03FF), (0x1F00, 0x1FFF)]),
    ("Hebrew", "he", 0x05D0,
     [(0x0590, 0x05FF), (0xFB1D, 0xFB4F)]),
    ("Kana", "ja", 0x3042,
     [(0x3040, 0x309F), (0x30A0, 0x30FF), (0x31F0, 0x31FF), (0xFF65, 0xFF9F)]),
    ("Hangul", "ko", 0xAC00,
     [(0x1100, 0x11FF), (0x3130, 0x318F), (0xA960, 0xA97F), (0xAC00, 0xD7AF), (0xD7B0, 0xD7FF)]),
    ("Thai", "th", 0x0E01,
     [(0x0E00, 0x0E7F)]),
    ("Armenian", "hy", 0x0531,
     [(0x0530, 0x058F), (0xFB13, 0xFB17)]),
    ("Bengali", "bn", 0x0995,
     [(0x0980, 0x09FF)]),
    ("Canadian", "iu", 0x1401,
     [(0x1400, 0x167F), (0x18B0, 0x18FF)]),
    ("Cyrillic", "ru", 0x0410,
     [(0x0400, 0x052F), (0x2DE0, 0x2DFF), (0xA640, 0xA69F)]),
    ("Devanagari", "hi", 0x0915,
     [(0x0900, 0x097F), (0xA8E0, 0xA8FF)]),
    ("Ethiopic", "am", 0x1200,
     [(0x1200, 0x139F), (0x2D80, 0x2DDF)]),
    ("Georgian", "ka", 0x10A0,
     [(0x10A0, 0x10FF), (0x1C90, 0x1CBF), (0x2D00, 0x2D2F)]),
    ("Gujarati", "gu", 0x0A95,
     [(0x0A80, 0x0AFF)]),
    ("Gurmukhi", "pa", 0x0A15,
     [(0x0A00, 0x0A7F)]),
    ("Khmer", "km", 0x1780,
     [(0x1780, 0x17FF), (0x19E0, 0x19FF)]),
    ("Kannada", "kn", 0x0C95,
     [(0x0C80, 0x0CFF)]),
    ("Malayalam", "ml", 0x0D15,
     [(0x0D00, 0x0D7F)]),
    ("Oriya", "or", 0x0B15,
     [(0x0B00, 0x0B7F)]),
    ("Sinhala", "si", 0x0D9A,
     [(0x0D80, 0x0DFF)]),
    ("Tamil", "ta", 0x0B95,
     [(0x0B80, 0x0BFF)]),
    ("Telugu", "te", 0x0C15,
     [(0x0C00, 0x0C7F)]),
    ("Tibetan", "bo", 0x0F40,
     [(0x0F00, 0x0FFF)]),
    ("Han", "zh-cn", 0x4E00,
     [(0x3000, 0x303F), (0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF), (0x20000, 0x2A6DF)]),
    ("Any", None, 0x1F600,
     [(0x0000, 0x10FFFF)]),
]

BANNER = "// GENERATED by tools/gen_fallback_data.py - do not edit by hand.\n"


def check_ranges():
    """Each script's ranges must contain the codepoint it was probed with.

    The ranges are the hand-written half, so they are the half that gets
    checked. A mistyped block shows up as a script whose own representative
    character falls outside it.
    """
    problems = []
    for label, _, codepoint, ranges in SCRIPTS:
        if not any(lo <= codepoint <= hi for lo, hi in ranges):
            problems.append("%s: U+%04X is outside its own ranges" % (label, codepoint))
    return problems


def main():
    problems = check_ranges()
    if problems:
        sys.exit("fallback ranges do not cover their own scripts:\n  " +
                 "\n  ".join(problems))

    out = [BANNER,
           "//\n// Per-script fallback: which Unicode ranges belong to which script, and\n"
           "// the fontconfig language whose answer covers it here. No font is\n"
           "// named; see tools/gen_fallback_data.py for why.\n\n",
           '#include "fallback_data.h"\n\nnamespace dwc\n{\n\n']

    for label, fc_lang, _, ranges in SCRIPTS:
        tag = label.replace(" ", "")
        out.append("constexpr FallbackRange k%sRanges[] = {\n" % tag)
        for lo, hi in ranges:
            out.append("    { .first = 0x%04X, .last = 0x%04X },\n" % (lo, hi))
        out.append("};\n\n")

    out.append("const FallbackEntry kFallbackEntries[] = {\n")
    for label, fc_lang, _, ranges in SCRIPTS:
        tag = label.replace(" ", "")
        out.append('    { .script = "%s", .fc_lang = %s, .ranges = k%sRanges,'
                   ' .range_count = %d },\n'
                   % (label, ('"%s"' % fc_lang) if fc_lang else "nullptr",
                      tag, len(ranges)))
    out.append("};\n\n")
    out.append("const unsigned kFallbackEntryCount =\n"
               "    sizeof(kFallbackEntries) / sizeof(kFallbackEntries[0]);\n")
    out.append("\n}  // namespace dwc\n")

    path = os.path.join(SRC, "fallback_data.cpp")
    open(path, "w", encoding="utf-8").write("".join(out))

    print("Generating the fallback table")
    print("  %-28s %d scripts, %d ranges"
          % (os.path.basename(path), len(SCRIPTS),
             sum(len(r) for _, _, _, r in SCRIPTS)))


if __name__ == "__main__":
    main()
