#!/usr/bin/env python3
"""
Emit linker version scripts for the bionic compatibility stubs.

Every symbol libdwritecore.so imports is versioned @LIBC and bound to a
specific file by the .gnu.version_r table. glibc's own libraries define
GLIBC_2.x versions, never LIBC, so the loader will not satisfy these
references from the host libc no matter what is in scope - each stub has to
declare a LIBC version of its own and export exactly the symbols the binary
expects from that file.

Reading the partition out of the binary keeps the scripts honest; transcribing
75 names by hand would not survive a different DWriteCore build.
"""

import os
import struct
import sys

from paths import BINARY, BIONIC_COMPAT as OUT

# Which stub provides the symbols that carry no version record.
UNVERSIONED_OWNER = {
    "__android_log_print": "liblog.so",
    "getrandom": "libc.so",
}


def sections(data):
    e_shoff = struct.unpack_from("<Q", data, 0x28)[0]
    es = struct.unpack_from("<H", data, 0x3A)[0]
    n = struct.unpack_from("<H", data, 0x3C)[0]
    sx = struct.unpack_from("<H", data, 0x3E)[0]

    def sh(index):
        b = e_shoff + index * es
        nm, _t, _f, addr, off, size = struct.unpack_from("<IIQQQQ", data, b)
        return dict(nm=nm, addr=addr, off=off, size=size)

    st = sh(sx)
    out = {}
    for i in range(n):
        s = sh(i)
        e = data.index(b"\0", st["off"] + s["nm"])
        out[data[st["off"] + s["nm"]:e].decode()] = s
    return out


def imports_by_file(data):
    sec = sections(data)
    dsym, dstr = sec[".dynsym"], sec[".dynstr"]
    vers, vneed = sec[".gnu.version"], sec[".gnu.version_r"]

    idx2file = {}
    off = vneed["off"]
    while True:
        _ver, cnt, file_off, aux, nxt = struct.unpack_from("<HHIII", data, off)
        e = data.index(b"\0", dstr["off"] + file_off)
        fname = data[dstr["off"] + file_off:e].decode()
        a = off + aux
        for _ in range(cnt):
            _h, _flags, other, _name, anext = struct.unpack_from("<IHHII", data, a)
            idx2file[other] = fname
            a += anext
            if not anext:
                break
        if not nxt:
            break
        off += nxt

    groups = {}
    for i in range(dsym["size"] // 24):
        o = dsym["off"] + i * 24
        nm, _info, _other, shndx, _val, _size = struct.unpack_from("<IBBHQQ", data, o)
        if shndx != 0:
            continue
        e = data.index(b"\0", dstr["off"] + nm)
        name = data[dstr["off"] + nm:e].decode()
        if not name:
            continue
        v = struct.unpack_from("<H", data, vers["off"] + i * 2)[0] & 0x7FFF
        f = idx2file.get(v)
        if f is None:
            f = UNVERSIONED_OWNER.get(name)
            if f is None:
                print("  warning: unversioned import %r has no assigned stub" % name)
                continue
        groups.setdefault(f, set()).add(name)
    return groups


def write_map(soname, symbols, versioned):
    stem = soname.replace(".so", "")
    path = os.path.join(OUT, stem + ".map")
    body = "\n".join("        %s;" % s for s in sorted(symbols))
    if versioned:
        # The version node must be named LIBC to match the binary's Verneed.
        text = ("/* GENERATED by tools/gen_bionic_maps.py - do not edit. */\n"
                "LIBC {\n    global:\n%s\n    local:\n        *;\n};\n" % body)
    else:
        text = ("/* GENERATED by tools/gen_bionic_maps.py - do not edit. */\n"
                "{\n    global:\n%s\n    local:\n        *;\n};\n" % body)
    open(path, "w").write(text)
    print("  %-12s %2d symbols -> %s" % (soname, len(symbols), os.path.basename(path)))


def main():
    data = open(BINARY, "rb").read()
    groups = imports_by_file(data)
    os.makedirs(OUT, exist_ok=True)
    print("Generating bionic stub version scripts:")
    for soname in ("libc.so", "libm.so", "libdl.so", "liblog.so"):
        syms = groups.get(soname, set())
        if not syms:
            continue
        # liblog's import carries no version record, so its stub stays unversioned.
        write_map(soname, syms, versioned=(soname != "liblog.so"))
    total = sum(len(v) for v in groups.values())
    print("  %d imports covered" % total)


if __name__ == "__main__":
    main()
