// GENERATED by tools/gen_factory_proxy.py - do not edit by hand.
//
// The proxy DWriteCoreCreateFactory hands out. Forwards everything to the
// real factory except the system-font getters, which the shipped library
// cannot answer because it has no way to enumerate fonts.
//
// Deriving from IDWriteFactory9 covers the whole chain: each IDWriteFactoryN
// derives from its predecessor, so this one vtable carries every slot and
// QueryInterface can return the same pointer for any of them.
#ifndef DWRITECORE_FACTORY_PROXY_H_INCLUDED
#define DWRITECORE_FACTORY_PROXY_H_INCLUDED
#include "dwrite_core.h"
#include "DWriteExperimental.h"

namespace dwc
{
class FactoryProxy final : public IDWriteFactory9
{
public:
    // Takes ownership of one reference on `real`.
    explicit FactoryProxy(IDWriteFactory9* real);
    IDWriteFactory9* real() const { return real_; }
    // IUnknown
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** object) override;
    ULONG STDMETHODCALLTYPE AddRef() override;
    ULONG STDMETHODCALLTYPE Release() override;
    // ---- IDWriteFactory ------------------------------------------
    HRESULT STDMETHODCALLTYPE GetSystemFontCollection(IDWriteFontCollection** fontCollection, BOOL checkForUpdates) override;  // overridden
    HRESULT STDMETHODCALLTYPE CreateCustomFontCollection(IDWriteFontCollectionLoader* collectionLoader, const void* collectionKey, UINT32 collectionKeySize, IDWriteFontCollection** fontCollection) override;
    HRESULT STDMETHODCALLTYPE RegisterFontCollectionLoader(IDWriteFontCollectionLoader* fontCollectionLoader) override;
    HRESULT STDMETHODCALLTYPE UnregisterFontCollectionLoader(IDWriteFontCollectionLoader* fontCollectionLoader) override;
    HRESULT STDMETHODCALLTYPE CreateFontFileReference(const WCHAR* filePath, const FILETIME* lastWriteTime, IDWriteFontFile** fontFile) override;
    HRESULT STDMETHODCALLTYPE CreateCustomFontFileReference(const void* fontFileReferenceKey, UINT32 fontFileReferenceKeySize, IDWriteFontFileLoader* fontFileLoader, IDWriteFontFile** fontFile) override;
    HRESULT STDMETHODCALLTYPE CreateFontFace(DWRITE_FONT_FACE_TYPE fontFaceType, UINT32 numberOfFiles, IDWriteFontFile* const* fontFiles, UINT32 faceIndex, DWRITE_FONT_SIMULATIONS fontFaceSimulationFlags, IDWriteFontFace** fontFace) override;
    HRESULT STDMETHODCALLTYPE CreateRenderingParams(IDWriteRenderingParams** renderingParams) override;
    HRESULT STDMETHODCALLTYPE CreateMonitorRenderingParams(HMONITOR monitor, IDWriteRenderingParams** renderingParams) override;
    HRESULT STDMETHODCALLTYPE CreateCustomRenderingParams(FLOAT gamma, FLOAT enhancedContrast, FLOAT clearTypeLevel, DWRITE_PIXEL_GEOMETRY pixelGeometry, DWRITE_RENDERING_MODE renderingMode, IDWriteRenderingParams** renderingParams) override;
    HRESULT STDMETHODCALLTYPE RegisterFontFileLoader(IDWriteFontFileLoader* fontFileLoader) override;
    HRESULT STDMETHODCALLTYPE UnregisterFontFileLoader(IDWriteFontFileLoader* fontFileLoader) override;
    HRESULT STDMETHODCALLTYPE CreateTextFormat(const WCHAR* fontFamilyName, IDWriteFontCollection* fontCollection, DWRITE_FONT_WEIGHT fontWeight, DWRITE_FONT_STYLE fontStyle, DWRITE_FONT_STRETCH fontStretch, FLOAT fontSize, const WCHAR* localeName, IDWriteTextFormat** textFormat) override;  // overridden
    HRESULT STDMETHODCALLTYPE CreateTypography(IDWriteTypography** typography) override;
    HRESULT STDMETHODCALLTYPE GetGdiInterop(IDWriteGdiInterop** gdiInterop) override;
    HRESULT STDMETHODCALLTYPE CreateTextLayout(const WCHAR* string, UINT32 stringLength, IDWriteTextFormat* textFormat, FLOAT maxWidth, FLOAT maxHeight, IDWriteTextLayout** textLayout) override;
    HRESULT STDMETHODCALLTYPE CreateGdiCompatibleTextLayout(const WCHAR* string, UINT32 stringLength, IDWriteTextFormat* textFormat, FLOAT layoutWidth, FLOAT layoutHeight, FLOAT pixelsPerDip, const DWRITE_MATRIX* transform, BOOL useGdiNatural, IDWriteTextLayout** textLayout) override;
    HRESULT STDMETHODCALLTYPE CreateEllipsisTrimmingSign(IDWriteTextFormat* textFormat, IDWriteInlineObject** trimmingSign) override;
    HRESULT STDMETHODCALLTYPE CreateTextAnalyzer(IDWriteTextAnalyzer** textAnalyzer) override;
    HRESULT STDMETHODCALLTYPE CreateNumberSubstitution(DWRITE_NUMBER_SUBSTITUTION_METHOD substitutionMethod, const WCHAR* localeName, BOOL ignoreUserOverride, IDWriteNumberSubstitution** numberSubstitution) override;
    HRESULT STDMETHODCALLTYPE CreateGlyphRunAnalysis(const DWRITE_GLYPH_RUN* glyphRun, FLOAT pixelsPerDip, const DWRITE_MATRIX* transform, DWRITE_RENDERING_MODE renderingMode, DWRITE_MEASURING_MODE measuringMode, FLOAT baselineOriginX, FLOAT baselineOriginY, IDWriteGlyphRunAnalysis** glyphRunAnalysis) override;
    // ---- IDWriteFactory1 -----------------------------------------
    HRESULT STDMETHODCALLTYPE GetEudcFontCollection(IDWriteFontCollection** fontCollection, BOOL checkForUpdates) override;
    HRESULT STDMETHODCALLTYPE CreateCustomRenderingParams(FLOAT gamma, FLOAT enhancedContrast, FLOAT enhancedContrastGrayscale, FLOAT clearTypeLevel, DWRITE_PIXEL_GEOMETRY pixelGeometry, DWRITE_RENDERING_MODE renderingMode, IDWriteRenderingParams1** renderingParams) override;
    // ---- IDWriteFactory2 -----------------------------------------
    HRESULT STDMETHODCALLTYPE GetSystemFontFallback(IDWriteFontFallback** fontFallback) override;  // overridden
    HRESULT STDMETHODCALLTYPE CreateFontFallbackBuilder(IDWriteFontFallbackBuilder** fontFallbackBuilder) override;
    HRESULT STDMETHODCALLTYPE TranslateColorGlyphRun(FLOAT baselineOriginX, FLOAT baselineOriginY, const DWRITE_GLYPH_RUN* glyphRun, const DWRITE_GLYPH_RUN_DESCRIPTION* glyphRunDescription, DWRITE_MEASURING_MODE measuringMode, const DWRITE_MATRIX* worldToDeviceTransform, UINT32 colorPaletteIndex, IDWriteColorGlyphRunEnumerator** colorLayers) override;
    HRESULT STDMETHODCALLTYPE CreateCustomRenderingParams(FLOAT gamma, FLOAT enhancedContrast, FLOAT grayscaleEnhancedContrast, FLOAT clearTypeLevel, DWRITE_PIXEL_GEOMETRY pixelGeometry, DWRITE_RENDERING_MODE renderingMode, DWRITE_GRID_FIT_MODE gridFitMode, IDWriteRenderingParams2** renderingParams) override;
    HRESULT STDMETHODCALLTYPE CreateGlyphRunAnalysis(const DWRITE_GLYPH_RUN* glyphRun, const DWRITE_MATRIX* transform, DWRITE_RENDERING_MODE renderingMode, DWRITE_MEASURING_MODE measuringMode, DWRITE_GRID_FIT_MODE gridFitMode, DWRITE_TEXT_ANTIALIAS_MODE antialiasMode, FLOAT baselineOriginX, FLOAT baselineOriginY, IDWriteGlyphRunAnalysis** glyphRunAnalysis) override;
    // ---- IDWriteFactory3 -----------------------------------------
    HRESULT STDMETHODCALLTYPE CreateGlyphRunAnalysis(const DWRITE_GLYPH_RUN* glyphRun, const DWRITE_MATRIX* transform, DWRITE_RENDERING_MODE1 renderingMode, DWRITE_MEASURING_MODE measuringMode, DWRITE_GRID_FIT_MODE gridFitMode, DWRITE_TEXT_ANTIALIAS_MODE antialiasMode, FLOAT baselineOriginX, FLOAT baselineOriginY, IDWriteGlyphRunAnalysis** glyphRunAnalysis) override;
    HRESULT STDMETHODCALLTYPE CreateCustomRenderingParams(FLOAT gamma, FLOAT enhancedContrast, FLOAT grayscaleEnhancedContrast, FLOAT clearTypeLevel, DWRITE_PIXEL_GEOMETRY pixelGeometry, DWRITE_RENDERING_MODE1 renderingMode, DWRITE_GRID_FIT_MODE gridFitMode, IDWriteRenderingParams3** renderingParams) override;
    HRESULT STDMETHODCALLTYPE CreateFontFaceReference(const WCHAR* filePath, const FILETIME* lastWriteTime, UINT32 faceIndex, DWRITE_FONT_SIMULATIONS fontSimulations, IDWriteFontFaceReference** fontFaceReference) override;
    HRESULT STDMETHODCALLTYPE CreateFontFaceReference(IDWriteFontFile* fontFile, UINT32 faceIndex, DWRITE_FONT_SIMULATIONS fontSimulations, IDWriteFontFaceReference** fontFaceReference) override;
    HRESULT STDMETHODCALLTYPE GetSystemFontSet(IDWriteFontSet** fontSet) override;  // overridden
    HRESULT STDMETHODCALLTYPE CreateFontSetBuilder(IDWriteFontSetBuilder** fontSetBuilder) override;
    HRESULT STDMETHODCALLTYPE CreateFontCollectionFromFontSet(IDWriteFontSet* fontSet, IDWriteFontCollection1** fontCollection) override;
    HRESULT STDMETHODCALLTYPE GetSystemFontCollection(BOOL includeDownloadableFonts, IDWriteFontCollection1** fontCollection, BOOL checkForUpdates) override;  // overridden
    HRESULT STDMETHODCALLTYPE GetFontDownloadQueue(IDWriteFontDownloadQueue** fontDownloadQueue) override;
    // ---- IDWriteFactory4 -----------------------------------------
    HRESULT STDMETHODCALLTYPE TranslateColorGlyphRun(D2D1_POINT_2F baselineOrigin, const DWRITE_GLYPH_RUN* glyphRun, const DWRITE_GLYPH_RUN_DESCRIPTION* glyphRunDescription, DWRITE_GLYPH_IMAGE_FORMATS desiredGlyphImageFormats, DWRITE_MEASURING_MODE measuringMode, const DWRITE_MATRIX* worldAndDpiTransform, UINT32 colorPaletteIndex, IDWriteColorGlyphRunEnumerator1** colorLayers) override;
    HRESULT STDMETHODCALLTYPE ComputeGlyphOrigins(const DWRITE_GLYPH_RUN* glyphRun, DWRITE_MEASURING_MODE measuringMode, D2D1_POINT_2F baselineOrigin, const DWRITE_MATRIX* worldAndDpiTransform, D2D1_POINT_2F* glyphOrigins) override;
    HRESULT STDMETHODCALLTYPE ComputeGlyphOrigins(const DWRITE_GLYPH_RUN* glyphRun, D2D1_POINT_2F baselineOrigin, D2D1_POINT_2F* glyphOrigins) override;
    // ---- IDWriteFactory5 -----------------------------------------
    HRESULT STDMETHODCALLTYPE CreateFontSetBuilder(IDWriteFontSetBuilder1** fontSetBuilder) override;
    HRESULT STDMETHODCALLTYPE CreateInMemoryFontFileLoader(IDWriteInMemoryFontFileLoader** newLoader) override;
    HRESULT STDMETHODCALLTYPE CreateHttpFontFileLoader(const WCHAR* referrerUrl, const WCHAR* extraHeaders, IDWriteRemoteFontFileLoader** newLoader) override;
    DWRITE_CONTAINER_TYPE STDMETHODCALLTYPE AnalyzeContainerType(const void* fileData, UINT32 fileDataSize) override;
    HRESULT STDMETHODCALLTYPE UnpackFontFile(DWRITE_CONTAINER_TYPE containerType, const void* fileData, UINT32 fileDataSize, IDWriteFontFileStream** unpackedFontStream) override;
    // ---- IDWriteFactory6 -----------------------------------------
    HRESULT STDMETHODCALLTYPE CreateFontFaceReference(IDWriteFontFile* fontFile, UINT32 faceIndex, DWRITE_FONT_SIMULATIONS fontSimulations, const DWRITE_FONT_AXIS_VALUE* fontAxisValues, UINT32 fontAxisValueCount, IDWriteFontFaceReference1** fontFaceReference) override;
    HRESULT STDMETHODCALLTYPE CreateFontResource(IDWriteFontFile* fontFile, UINT32 faceIndex, IDWriteFontResource** fontResource) override;
    HRESULT STDMETHODCALLTYPE GetSystemFontSet(BOOL includeDownloadableFonts, IDWriteFontSet1** fontSet) override;  // overridden
    HRESULT STDMETHODCALLTYPE GetSystemFontCollection(BOOL includeDownloadableFonts, DWRITE_FONT_FAMILY_MODEL fontFamilyModel, IDWriteFontCollection2** fontCollection) override;  // overridden
    HRESULT STDMETHODCALLTYPE CreateFontCollectionFromFontSet(IDWriteFontSet* fontSet, DWRITE_FONT_FAMILY_MODEL fontFamilyModel, IDWriteFontCollection2** fontCollection) override;
    HRESULT STDMETHODCALLTYPE CreateFontSetBuilder(IDWriteFontSetBuilder2** fontSetBuilder) override;
    HRESULT STDMETHODCALLTYPE CreateTextFormat(const WCHAR* fontFamilyName, IDWriteFontCollection* fontCollection, const DWRITE_FONT_AXIS_VALUE* fontAxisValues, UINT32 fontAxisValueCount, FLOAT fontSize, const WCHAR* localeName, IDWriteTextFormat3** textFormat) override;  // overridden
    // ---- IDWriteFactory7 -----------------------------------------
    HRESULT STDMETHODCALLTYPE GetSystemFontSet(BOOL includeDownloadableFonts, IDWriteFontSet2** fontSet) override;  // overridden
    HRESULT STDMETHODCALLTYPE GetSystemFontCollection(BOOL includeDownloadableFonts, DWRITE_FONT_FAMILY_MODEL fontFamilyModel, IDWriteFontCollection3** fontCollection) override;  // overridden
    // ---- IDWriteFactory8 -----------------------------------------
    HRESULT STDMETHODCALLTYPE TranslateColorGlyphRun(D2D1_POINT_2F baselineOrigin, const DWRITE_GLYPH_RUN* glyphRun, const DWRITE_GLYPH_RUN_DESCRIPTION* glyphRunDescription, DWRITE_GLYPH_IMAGE_FORMATS desiredGlyphImageFormats, DWRITE_PAINT_FEATURE_LEVEL paintFeatureLevel, DWRITE_MEASURING_MODE measuringMode, const DWRITE_MATRIX* worldAndDpiTransform, UINT32 colorPaletteIndex, IDWriteColorGlyphRunEnumerator1** colorEnumerator) override;
    // ---- IDWriteFactory9 -----------------------------------------
    HRESULT STDMETHODCALLTYPE CreateFontSetBuilderWithCache(IDWriteCachedData* cachedData, IDWriteFontSetBuilderWithCache** builder) override;
    HRESULT STDMETHODCALLTYPE CreateFontSetFromCachedData(IDWriteCachedData* cachedData, IDWriteFontSet5** fontSet) override;

private:
    // Private and non-virtual. Non-virtual because a virtual destructor
    // would append a slot to a vtable that has to match IDWriteFactory9's
    // layout exactly. Private because the only legitimate destruction is
    // `delete this` from Release(), which is inside the class.
    ~FactoryProxy();

    IDWriteFactory9* real_;
    long refs_;
    // Lazily built font set and its collection views. Opaque here; the
    // type and everything that fills it live in src/system_fonts.cpp.
    struct SystemFonts* fonts_;
};

}  // namespace dwc

#endif  // DWRITECORE_FACTORY_PROXY_H_INCLUDED
