// GENERATED by tools/gen_factory_proxy.py - do not edit by hand.
//
// One forwarding definition per method the proxy does not answer itself.
// The overridden ones are defined in src/factory_proxy_overrides.cpp.
//
// Most of the casts below are redundant. Which ones are load-bearing
// depends on which hidden overloads the SDK headers happen to
// re-expose, so none of them is dropped; see the note in the
// generator. Analysis is told once here instead of at every call.

// ReSharper disable CppRedundantCastExpression

#include "factory_proxy.h"

namespace dwc
{

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateCustomFontCollection(IDWriteFontCollectionLoader* const collectionLoader, const void* const collectionKey, const UINT32 collectionKeySize, IDWriteFontCollection** const fontCollection)
{
    return static_cast<IDWriteFactory*>(real_)->CreateCustomFontCollection(collectionLoader, collectionKey, collectionKeySize, fontCollection);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::RegisterFontCollectionLoader(IDWriteFontCollectionLoader* const fontCollectionLoader)
{
    return static_cast<IDWriteFactory*>(real_)->RegisterFontCollectionLoader(fontCollectionLoader);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::UnregisterFontCollectionLoader(IDWriteFontCollectionLoader* const fontCollectionLoader)
{
    return static_cast<IDWriteFactory*>(real_)->UnregisterFontCollectionLoader(fontCollectionLoader);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontFileReference(const WCHAR* const filePath, const FILETIME* const lastWriteTime, IDWriteFontFile** const fontFile)
{
    return static_cast<IDWriteFactory*>(real_)->CreateFontFileReference(filePath, lastWriteTime, fontFile);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateCustomFontFileReference(const void* const fontFileReferenceKey, const UINT32 fontFileReferenceKeySize, IDWriteFontFileLoader* const fontFileLoader, IDWriteFontFile** const fontFile)
{
    return static_cast<IDWriteFactory*>(real_)->CreateCustomFontFileReference(fontFileReferenceKey, fontFileReferenceKeySize, fontFileLoader, fontFile);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontFace(const DWRITE_FONT_FACE_TYPE fontFaceType, const UINT32 numberOfFiles, IDWriteFontFile* const* const fontFiles, const UINT32 faceIndex, const DWRITE_FONT_SIMULATIONS fontFaceSimulationFlags, IDWriteFontFace** const fontFace)
{
    return static_cast<IDWriteFactory*>(real_)->CreateFontFace(fontFaceType, numberOfFiles, fontFiles, faceIndex, fontFaceSimulationFlags, fontFace);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateRenderingParams(IDWriteRenderingParams** const renderingParams)
{
    return static_cast<IDWriteFactory*>(real_)->CreateRenderingParams(renderingParams);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateMonitorRenderingParams(const HMONITOR monitor, IDWriteRenderingParams** const renderingParams)
{
    return static_cast<IDWriteFactory*>(real_)->CreateMonitorRenderingParams(monitor, renderingParams);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateCustomRenderingParams(const FLOAT gamma, const FLOAT enhancedContrast, const FLOAT clearTypeLevel, const DWRITE_PIXEL_GEOMETRY pixelGeometry, const DWRITE_RENDERING_MODE renderingMode, IDWriteRenderingParams** const renderingParams)
{
    return static_cast<IDWriteFactory*>(real_)->CreateCustomRenderingParams(gamma, enhancedContrast, clearTypeLevel, pixelGeometry, renderingMode, renderingParams);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::RegisterFontFileLoader(IDWriteFontFileLoader* const fontFileLoader)
{
    return static_cast<IDWriteFactory*>(real_)->RegisterFontFileLoader(fontFileLoader);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::UnregisterFontFileLoader(IDWriteFontFileLoader* const fontFileLoader)
{
    return static_cast<IDWriteFactory*>(real_)->UnregisterFontFileLoader(fontFileLoader);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateTypography(IDWriteTypography** const typography)
{
    return static_cast<IDWriteFactory*>(real_)->CreateTypography(typography);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::GetGdiInterop(IDWriteGdiInterop** const gdiInterop)
{
    return static_cast<IDWriteFactory*>(real_)->GetGdiInterop(gdiInterop);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateTextLayout(const WCHAR* const string, const UINT32 stringLength, IDWriteTextFormat* const textFormat, const FLOAT maxWidth, const FLOAT maxHeight, IDWriteTextLayout** const textLayout)
{
    return static_cast<IDWriteFactory*>(real_)->CreateTextLayout(string, stringLength, textFormat, maxWidth, maxHeight, textLayout);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateGdiCompatibleTextLayout(const WCHAR* const string, const UINT32 stringLength, IDWriteTextFormat* const textFormat, const FLOAT layoutWidth, const FLOAT layoutHeight, const FLOAT pixelsPerDip, const DWRITE_MATRIX* const transform, const BOOL useGdiNatural, IDWriteTextLayout** const textLayout)
{
    return static_cast<IDWriteFactory*>(real_)->CreateGdiCompatibleTextLayout(string, stringLength, textFormat, layoutWidth, layoutHeight, pixelsPerDip, transform, useGdiNatural, textLayout);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateEllipsisTrimmingSign(IDWriteTextFormat* const textFormat, IDWriteInlineObject** const trimmingSign)
{
    return static_cast<IDWriteFactory*>(real_)->CreateEllipsisTrimmingSign(textFormat, trimmingSign);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateTextAnalyzer(IDWriteTextAnalyzer** const textAnalyzer)
{
    return static_cast<IDWriteFactory*>(real_)->CreateTextAnalyzer(textAnalyzer);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateNumberSubstitution(const DWRITE_NUMBER_SUBSTITUTION_METHOD substitutionMethod, const WCHAR* const localeName, const BOOL ignoreUserOverride, IDWriteNumberSubstitution** const numberSubstitution)
{
    return static_cast<IDWriteFactory*>(real_)->CreateNumberSubstitution(substitutionMethod, localeName, ignoreUserOverride, numberSubstitution);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateGlyphRunAnalysis(const DWRITE_GLYPH_RUN* const glyphRun, const FLOAT pixelsPerDip, const DWRITE_MATRIX* const transform, const DWRITE_RENDERING_MODE renderingMode, const DWRITE_MEASURING_MODE measuringMode, const FLOAT baselineOriginX, const FLOAT baselineOriginY, IDWriteGlyphRunAnalysis** const glyphRunAnalysis)
{
    return static_cast<IDWriteFactory*>(real_)->CreateGlyphRunAnalysis(glyphRun, pixelsPerDip, transform, renderingMode, measuringMode, baselineOriginX, baselineOriginY, glyphRunAnalysis);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::GetEudcFontCollection(IDWriteFontCollection** const fontCollection, const BOOL checkForUpdates)
{
    return static_cast<IDWriteFactory1*>(real_)->GetEudcFontCollection(fontCollection, checkForUpdates);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateCustomRenderingParams(const FLOAT gamma, const FLOAT enhancedContrast, const FLOAT enhancedContrastGrayscale, const FLOAT clearTypeLevel, const DWRITE_PIXEL_GEOMETRY pixelGeometry, const DWRITE_RENDERING_MODE renderingMode, IDWriteRenderingParams1** const renderingParams)
{
    return static_cast<IDWriteFactory1*>(real_)->CreateCustomRenderingParams(gamma, enhancedContrast, enhancedContrastGrayscale, clearTypeLevel, pixelGeometry, renderingMode, renderingParams);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontFallbackBuilder(IDWriteFontFallbackBuilder** const fontFallbackBuilder)
{
    return static_cast<IDWriteFactory2*>(real_)->CreateFontFallbackBuilder(fontFallbackBuilder);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::TranslateColorGlyphRun(const FLOAT baselineOriginX, const FLOAT baselineOriginY, const DWRITE_GLYPH_RUN* const glyphRun, const DWRITE_GLYPH_RUN_DESCRIPTION* const glyphRunDescription, const DWRITE_MEASURING_MODE measuringMode, const DWRITE_MATRIX* const worldToDeviceTransform, const UINT32 colorPaletteIndex, IDWriteColorGlyphRunEnumerator** const colorLayers)
{
    return static_cast<IDWriteFactory2*>(real_)->TranslateColorGlyphRun(baselineOriginX, baselineOriginY, glyphRun, glyphRunDescription, measuringMode, worldToDeviceTransform, colorPaletteIndex, colorLayers);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateCustomRenderingParams(const FLOAT gamma, const FLOAT enhancedContrast, const FLOAT grayscaleEnhancedContrast, const FLOAT clearTypeLevel, const DWRITE_PIXEL_GEOMETRY pixelGeometry, const DWRITE_RENDERING_MODE renderingMode, const DWRITE_GRID_FIT_MODE gridFitMode, IDWriteRenderingParams2** const renderingParams)
{
    return static_cast<IDWriteFactory2*>(real_)->CreateCustomRenderingParams(gamma, enhancedContrast, grayscaleEnhancedContrast, clearTypeLevel, pixelGeometry, renderingMode, gridFitMode, renderingParams);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateGlyphRunAnalysis(const DWRITE_GLYPH_RUN* const glyphRun, const DWRITE_MATRIX* const transform, const DWRITE_RENDERING_MODE renderingMode, const DWRITE_MEASURING_MODE measuringMode, const DWRITE_GRID_FIT_MODE gridFitMode, const DWRITE_TEXT_ANTIALIAS_MODE antialiasMode, const FLOAT baselineOriginX, const FLOAT baselineOriginY, IDWriteGlyphRunAnalysis** const glyphRunAnalysis)
{
    return static_cast<IDWriteFactory2*>(real_)->CreateGlyphRunAnalysis(glyphRun, transform, renderingMode, measuringMode, gridFitMode, antialiasMode, baselineOriginX, baselineOriginY, glyphRunAnalysis);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateGlyphRunAnalysis(const DWRITE_GLYPH_RUN* const glyphRun, const DWRITE_MATRIX* const transform, const DWRITE_RENDERING_MODE1 renderingMode, const DWRITE_MEASURING_MODE measuringMode, const DWRITE_GRID_FIT_MODE gridFitMode, const DWRITE_TEXT_ANTIALIAS_MODE antialiasMode, const FLOAT baselineOriginX, const FLOAT baselineOriginY, IDWriteGlyphRunAnalysis** const glyphRunAnalysis)
{
    return static_cast<IDWriteFactory3*>(real_)->CreateGlyphRunAnalysis(glyphRun, transform, renderingMode, measuringMode, gridFitMode, antialiasMode, baselineOriginX, baselineOriginY, glyphRunAnalysis);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateCustomRenderingParams(const FLOAT gamma, const FLOAT enhancedContrast, const FLOAT grayscaleEnhancedContrast, const FLOAT clearTypeLevel, const DWRITE_PIXEL_GEOMETRY pixelGeometry, const DWRITE_RENDERING_MODE1 renderingMode, const DWRITE_GRID_FIT_MODE gridFitMode, IDWriteRenderingParams3** const renderingParams)
{
    return static_cast<IDWriteFactory3*>(real_)->CreateCustomRenderingParams(gamma, enhancedContrast, grayscaleEnhancedContrast, clearTypeLevel, pixelGeometry, renderingMode, gridFitMode, renderingParams);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontFaceReference(const WCHAR* const filePath, const FILETIME* const lastWriteTime, const UINT32 faceIndex, const DWRITE_FONT_SIMULATIONS fontSimulations, IDWriteFontFaceReference** const fontFaceReference)
{
    return static_cast<IDWriteFactory3*>(real_)->CreateFontFaceReference(filePath, lastWriteTime, faceIndex, fontSimulations, fontFaceReference);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontFaceReference(IDWriteFontFile* const fontFile, const UINT32 faceIndex, const DWRITE_FONT_SIMULATIONS fontSimulations, IDWriteFontFaceReference** const fontFaceReference)
{
    return static_cast<IDWriteFactory3*>(real_)->CreateFontFaceReference(fontFile, faceIndex, fontSimulations, fontFaceReference);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontSetBuilder(IDWriteFontSetBuilder** const fontSetBuilder)
{
    return static_cast<IDWriteFactory3*>(real_)->CreateFontSetBuilder(fontSetBuilder);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontCollectionFromFontSet(IDWriteFontSet* const fontSet, IDWriteFontCollection1** const fontCollection)
{
    return static_cast<IDWriteFactory3*>(real_)->CreateFontCollectionFromFontSet(fontSet, fontCollection);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::GetFontDownloadQueue(IDWriteFontDownloadQueue** const fontDownloadQueue)
{
    return static_cast<IDWriteFactory3*>(real_)->GetFontDownloadQueue(fontDownloadQueue);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::TranslateColorGlyphRun(const D2D1_POINT_2F baselineOrigin, const DWRITE_GLYPH_RUN* const glyphRun, const DWRITE_GLYPH_RUN_DESCRIPTION* const glyphRunDescription, const DWRITE_GLYPH_IMAGE_FORMATS desiredGlyphImageFormats, const DWRITE_MEASURING_MODE measuringMode, const DWRITE_MATRIX* const worldAndDpiTransform, const UINT32 colorPaletteIndex, IDWriteColorGlyphRunEnumerator1** const colorLayers)
{
    return static_cast<IDWriteFactory4*>(real_)->TranslateColorGlyphRun(baselineOrigin, glyphRun, glyphRunDescription, desiredGlyphImageFormats, measuringMode, worldAndDpiTransform, colorPaletteIndex, colorLayers);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::ComputeGlyphOrigins(const DWRITE_GLYPH_RUN* const glyphRun, const DWRITE_MEASURING_MODE measuringMode, const D2D1_POINT_2F baselineOrigin, const DWRITE_MATRIX* const worldAndDpiTransform, D2D1_POINT_2F* const glyphOrigins)
{
    return static_cast<IDWriteFactory4*>(real_)->ComputeGlyphOrigins(glyphRun, measuringMode, baselineOrigin, worldAndDpiTransform, glyphOrigins);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::ComputeGlyphOrigins(const DWRITE_GLYPH_RUN* const glyphRun, const D2D1_POINT_2F baselineOrigin, D2D1_POINT_2F* const glyphOrigins)
{
    return static_cast<IDWriteFactory4*>(real_)->ComputeGlyphOrigins(glyphRun, baselineOrigin, glyphOrigins);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontSetBuilder(IDWriteFontSetBuilder1** const fontSetBuilder)
{
    return static_cast<IDWriteFactory5*>(real_)->CreateFontSetBuilder(fontSetBuilder);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateInMemoryFontFileLoader(IDWriteInMemoryFontFileLoader** const newLoader)
{
    return static_cast<IDWriteFactory5*>(real_)->CreateInMemoryFontFileLoader(newLoader);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateHttpFontFileLoader(const WCHAR* const referrerUrl, const WCHAR* const extraHeaders, IDWriteRemoteFontFileLoader** const newLoader)
{
    return static_cast<IDWriteFactory5*>(real_)->CreateHttpFontFileLoader(referrerUrl, extraHeaders, newLoader);
}

DWRITE_CONTAINER_TYPE STDMETHODCALLTYPE FactoryProxy::AnalyzeContainerType(const void* const fileData, const UINT32 fileDataSize)
{
    return static_cast<IDWriteFactory5*>(real_)->AnalyzeContainerType(fileData, fileDataSize);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::UnpackFontFile(const DWRITE_CONTAINER_TYPE containerType, const void* const fileData, const UINT32 fileDataSize, IDWriteFontFileStream** const unpackedFontStream)
{
    return static_cast<IDWriteFactory5*>(real_)->UnpackFontFile(containerType, fileData, fileDataSize, unpackedFontStream);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontFaceReference(IDWriteFontFile* const fontFile, const UINT32 faceIndex, const DWRITE_FONT_SIMULATIONS fontSimulations, const DWRITE_FONT_AXIS_VALUE* const fontAxisValues, const UINT32 fontAxisValueCount, IDWriteFontFaceReference1** const fontFaceReference)
{
    return static_cast<IDWriteFactory6*>(real_)->CreateFontFaceReference(fontFile, faceIndex, fontSimulations, fontAxisValues, fontAxisValueCount, fontFaceReference);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontResource(IDWriteFontFile* const fontFile, const UINT32 faceIndex, IDWriteFontResource** const fontResource)
{
    return static_cast<IDWriteFactory6*>(real_)->CreateFontResource(fontFile, faceIndex, fontResource);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontCollectionFromFontSet(IDWriteFontSet* const fontSet, const DWRITE_FONT_FAMILY_MODEL fontFamilyModel, IDWriteFontCollection2** const fontCollection)
{
    return static_cast<IDWriteFactory6*>(real_)->CreateFontCollectionFromFontSet(fontSet, fontFamilyModel, fontCollection);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontSetBuilder(IDWriteFontSetBuilder2** const fontSetBuilder)
{
    return static_cast<IDWriteFactory6*>(real_)->CreateFontSetBuilder(fontSetBuilder);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::TranslateColorGlyphRun(const D2D1_POINT_2F baselineOrigin, const DWRITE_GLYPH_RUN* const glyphRun, const DWRITE_GLYPH_RUN_DESCRIPTION* const glyphRunDescription, const DWRITE_GLYPH_IMAGE_FORMATS desiredGlyphImageFormats, const DWRITE_PAINT_FEATURE_LEVEL paintFeatureLevel, const DWRITE_MEASURING_MODE measuringMode, const DWRITE_MATRIX* const worldAndDpiTransform, const UINT32 colorPaletteIndex, IDWriteColorGlyphRunEnumerator1** const colorEnumerator)
{
    return static_cast<IDWriteFactory8*>(real_)->TranslateColorGlyphRun(baselineOrigin, glyphRun, glyphRunDescription, desiredGlyphImageFormats, paintFeatureLevel, measuringMode, worldAndDpiTransform, colorPaletteIndex, colorEnumerator);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontSetBuilderWithCache(IDWriteCachedData* const cachedData, IDWriteFontSetBuilderWithCache** const builder)
{
    return static_cast<IDWriteFactory9*>(real_)->CreateFontSetBuilderWithCache(cachedData, builder);
}

HRESULT STDMETHODCALLTYPE FactoryProxy::CreateFontSetFromCachedData(IDWriteCachedData* const cachedData, IDWriteFontSet5** const fontSet)
{
    return static_cast<IDWriteFactory9*>(real_)->CreateFontSetFromCachedData(cachedData, fontSet);
}

}  // namespace dwc
