// GENERATED by tools/gen_fallback_data.py - do not edit by hand.
//
// Per-script fallback: which Unicode ranges belong to which script, and
// the fontconfig language whose answer covers it here. No font is
// named; see tools/gen_fallback_data.py for why.

#include "fallback_data.h"

namespace dwc
{

constexpr FallbackRange kArabicRanges[] = {
    { .first = 0x0600, .last = 0x06FF },
    { .first = 0x0750, .last = 0x077F },
    { .first = 0x08A0, .last = 0x08FF },
    { .first = 0xFB50, .last = 0xFDFF },
    { .first = 0xFE70, .last = 0xFEFF },
};

constexpr FallbackRange kGreekRanges[] = {
    { .first = 0x0370, .last = 0x03FF },
    { .first = 0x1F00, .last = 0x1FFF },
};

constexpr FallbackRange kHebrewRanges[] = {
    { .first = 0x0590, .last = 0x05FF },
    { .first = 0xFB1D, .last = 0xFB4F },
};

constexpr FallbackRange kKanaRanges[] = {
    { .first = 0x3040, .last = 0x309F },
    { .first = 0x30A0, .last = 0x30FF },
    { .first = 0x31F0, .last = 0x31FF },
    { .first = 0xFF65, .last = 0xFF9F },
};

constexpr FallbackRange kHangulRanges[] = {
    { .first = 0x1100, .last = 0x11FF },
    { .first = 0x3130, .last = 0x318F },
    { .first = 0xA960, .last = 0xA97F },
    { .first = 0xAC00, .last = 0xD7AF },
    { .first = 0xD7B0, .last = 0xD7FF },
};

constexpr FallbackRange kThaiRanges[] = {
    { .first = 0x0E00, .last = 0x0E7F },
};

constexpr FallbackRange kArmenianRanges[] = {
    { .first = 0x0530, .last = 0x058F },
    { .first = 0xFB13, .last = 0xFB17 },
};

constexpr FallbackRange kBengaliRanges[] = {
    { .first = 0x0980, .last = 0x09FF },
};

constexpr FallbackRange kCanadianRanges[] = {
    { .first = 0x1400, .last = 0x167F },
    { .first = 0x18B0, .last = 0x18FF },
};

constexpr FallbackRange kCyrillicRanges[] = {
    { .first = 0x0400, .last = 0x052F },
    { .first = 0x2DE0, .last = 0x2DFF },
    { .first = 0xA640, .last = 0xA69F },
};

constexpr FallbackRange kDevanagariRanges[] = {
    { .first = 0x0900, .last = 0x097F },
    { .first = 0xA8E0, .last = 0xA8FF },
};

constexpr FallbackRange kEthiopicRanges[] = {
    { .first = 0x1200, .last = 0x139F },
    { .first = 0x2D80, .last = 0x2DDF },
};

constexpr FallbackRange kGeorgianRanges[] = {
    { .first = 0x10A0, .last = 0x10FF },
    { .first = 0x1C90, .last = 0x1CBF },
    { .first = 0x2D00, .last = 0x2D2F },
};

constexpr FallbackRange kGujaratiRanges[] = {
    { .first = 0x0A80, .last = 0x0AFF },
};

constexpr FallbackRange kGurmukhiRanges[] = {
    { .first = 0x0A00, .last = 0x0A7F },
};

constexpr FallbackRange kKhmerRanges[] = {
    { .first = 0x1780, .last = 0x17FF },
    { .first = 0x19E0, .last = 0x19FF },
};

constexpr FallbackRange kKannadaRanges[] = {
    { .first = 0x0C80, .last = 0x0CFF },
};

constexpr FallbackRange kMalayalamRanges[] = {
    { .first = 0x0D00, .last = 0x0D7F },
};

constexpr FallbackRange kOriyaRanges[] = {
    { .first = 0x0B00, .last = 0x0B7F },
};

constexpr FallbackRange kSinhalaRanges[] = {
    { .first = 0x0D80, .last = 0x0DFF },
};

constexpr FallbackRange kTamilRanges[] = {
    { .first = 0x0B80, .last = 0x0BFF },
};

constexpr FallbackRange kTeluguRanges[] = {
    { .first = 0x0C00, .last = 0x0C7F },
};

constexpr FallbackRange kTibetanRanges[] = {
    { .first = 0x0F00, .last = 0x0FFF },
};

constexpr FallbackRange kHanRanges[] = {
    { .first = 0x3000, .last = 0x303F },
    { .first = 0x3400, .last = 0x4DBF },
    { .first = 0x4E00, .last = 0x9FFF },
    { .first = 0xF900, .last = 0xFAFF },
    { .first = 0x20000, .last = 0x2A6DF },
};

constexpr FallbackRange kAnyRanges[] = {
    { .first = 0x0000, .last = 0x10FFFF },
};

const FallbackEntry kFallbackEntries[] = {
    { .script = "Arabic", .fc_lang = "ar", .ranges = kArabicRanges, .range_count = 5 },
    { .script = "Greek", .fc_lang = "el", .ranges = kGreekRanges, .range_count = 2 },
    { .script = "Hebrew", .fc_lang = "he", .ranges = kHebrewRanges, .range_count = 2 },
    { .script = "Kana", .fc_lang = "ja", .ranges = kKanaRanges, .range_count = 4 },
    { .script = "Hangul", .fc_lang = "ko", .ranges = kHangulRanges, .range_count = 5 },
    { .script = "Thai", .fc_lang = "th", .ranges = kThaiRanges, .range_count = 1 },
    { .script = "Armenian", .fc_lang = "hy", .ranges = kArmenianRanges, .range_count = 2 },
    { .script = "Bengali", .fc_lang = "bn", .ranges = kBengaliRanges, .range_count = 1 },
    { .script = "Canadian", .fc_lang = "iu", .ranges = kCanadianRanges, .range_count = 2 },
    { .script = "Cyrillic", .fc_lang = "ru", .ranges = kCyrillicRanges, .range_count = 3 },
    { .script = "Devanagari", .fc_lang = "hi", .ranges = kDevanagariRanges, .range_count = 2 },
    { .script = "Ethiopic", .fc_lang = "am", .ranges = kEthiopicRanges, .range_count = 2 },
    { .script = "Georgian", .fc_lang = "ka", .ranges = kGeorgianRanges, .range_count = 3 },
    { .script = "Gujarati", .fc_lang = "gu", .ranges = kGujaratiRanges, .range_count = 1 },
    { .script = "Gurmukhi", .fc_lang = "pa", .ranges = kGurmukhiRanges, .range_count = 1 },
    { .script = "Khmer", .fc_lang = "km", .ranges = kKhmerRanges, .range_count = 2 },
    { .script = "Kannada", .fc_lang = "kn", .ranges = kKannadaRanges, .range_count = 1 },
    { .script = "Malayalam", .fc_lang = "ml", .ranges = kMalayalamRanges, .range_count = 1 },
    { .script = "Oriya", .fc_lang = "or", .ranges = kOriyaRanges, .range_count = 1 },
    { .script = "Sinhala", .fc_lang = "si", .ranges = kSinhalaRanges, .range_count = 1 },
    { .script = "Tamil", .fc_lang = "ta", .ranges = kTamilRanges, .range_count = 1 },
    { .script = "Telugu", .fc_lang = "te", .ranges = kTeluguRanges, .range_count = 1 },
    { .script = "Tibetan", .fc_lang = "bo", .ranges = kTibetanRanges, .range_count = 1 },
    { .script = "Han", .fc_lang = "zh-cn", .ranges = kHanRanges, .range_count = 5 },
    { .script = "Any", .fc_lang = nullptr, .ranges = kAnyRanges, .range_count = 1 },
};

const unsigned kFallbackEntryCount =
    sizeof(kFallbackEntries) / sizeof(kFallbackEntries[0]);

}  // namespace dwc
